import {
  erpAccountingEntryPageSchema,
  erpAccountingEntrySchema,
  erpAccountingProvisionListSchema,
  erpAccountingProvisionSchema,
  erpAccountingAccountSchema,
  erpAccountingJournalSchema,
  erpAccountingPeriodSchema,
  erpAccountingReferencesSchema,
  erpAccountingReviewTaskListSchema,
  erpAccountingReviewTaskSchema,
  erpAccountingReviewAccountSchema,
  erpAccountingReviewDossierSchema,
  erpAccountingReviewExportSchema,
  erpBalanceReportSchema,
  erpChequeAlertsSchema,
  erpChequeBookListSchema,
  erpChequeBookSchema,
  erpChequeDepositEligibleListSchema,
  erpChequeDepositSlipListSchema,
  erpChequeDepositSlipSchema,
  erpChequePageSchema,
  erpChequeReconciliationCandidatesSchema,
  erpChequeSchema,
  erpChequeSummarySchema,
  erpCreditNotePageSchema,
  erpCreditNoteSchema,
  erpContextSchema,
  erpDocumentContentSchema,
  erpDocumentListSchema,
  erpDocumentSchema,
  erpExpenseNoteListSchema,
  erpExpenseNoteSchema,
  erpEligibleInvoicePageSchema,
  erpInvoicePageSchema,
  erpInvoiceReadSchema,
  erpInvoiceSchema,
  erpGrandLivreReportSchema,
  erpExerciseClosingResultSchema,
  erpExerciseListSchema,
  erpExerciseSchema,
  erpFecExportSchema,
  erpFecImportResultSchema,
  erpFinancialStatementsSchema,
  erpFiscalDeadlineListSchema,
  erpFiscalDeadlineSchema,
  erpFileExportSchema,
  erpLiasseDeleteResultSchema,
  erpLiasseExportSchema,
  erpLiasseRowSchema,
  erpLiasseTableDetailSchema,
  erpLiasseTableSummaryListSchema,
  erpLiasseValidationSchema,
  erpRegulatorySubmissionListSchema,
  erpRegulatorySubmissionSchema,
  erpLettrageMatchSchema,
  erpLettrageSuggestionsSchema,
  erpTaxDeclarationListSchema,
  erpTaxDeclarationSchema,
  erpTaxPaymentCandidateListSchema,
  erpTaxPaymentListSchema,
  erpTaxPaymentSchema,
  erpTvaProrataPeriodListSchema,
  erpTvaProrataPeriodSchema,
  erpAnnualTvaProrataSchema,
  erpTvaProrataPostingSchema,
  hrAccessAdministrationSchema,
  hrAccessContextSchema,
  hrAccessGrantSchema,
  hrContractAmendmentSchema,
  hrCostCenterListSchema,
  hrCostCenterSchema,
  hrCoreSummarySchema,
  hrDepartmentListSchema,
  hrDepartmentSchema,
  hrEmployeeBankAccountSchema,
  hrEmployeeDependantSchema,
  hrEmployeeDetailSchema,
  hrEmployeeEmergencyContactSchema,
  hrEmployeeImportCommitResultSchema,
  hrEmployeeImportPreviewSchema,
  hrEmployeeImportTemplateSchema,
  hrEmployeeListSchema,
  hrEmployeePrivateProfileSchema,
  hrEmployeeAssignmentSchema,
  hrEmployeeDocumentSchema,
  hrDocumentContentSchema,
  hrDeadlineCenterSchema,
  hrEmploymentContractSchema,
  hrEstablishmentListSchema,
  hrEstablishmentSchema,
  hrGradeListSchema,
  hrGradeSchema,
  hrJobPositionListSchema,
  hrJobPositionSchema,
  hrLifecycleJourneyListSchema,
  hrLifecycleJourneySchema,
  hrLifecycleTaskSchema,
  hrTeamListSchema,
  hrTeamSchema,
  hrWorkLocationListSchema,
  hrWorkLocationSchema,
  marketingAutomationListSchema,
  marketingAutomationSchema,
  marketingCampaignListSchema,
  marketingCampaignSchema,
  marketingContactListSchema,
  marketingContactSchema,
  marketingEventListSchema,
  marketingEventSchema,
  marketingOverviewSchema,
  marketingScoringRuleListSchema,
  marketingScoringRuleSchema,
  marketingSegmentListSchema,
  marketingSegmentSchema,
  marketingSegmentSyncResultSchema,
  marketingTierImportResultSchema,
  payrollComponentListSchema,
  payrollControlDefinitionListSchema,
  payrollLegalSourceListSchema,
  payrollRegulatorySeedResultSchema,
  payrollRegulatorySummarySchema,
  payrollRuleListSchema,
  erpMarocRouteIds,
  erpMarocUpstreamRoutes,
  erpPaymentPageSchema,
  erpPaymentSchema,
  erpProductListSchema,
  erpProductSchema,
  erpPurchaseOrderListSchema,
  erpPurchaseOrderSchema,
  erpPurchaseReceiptListSchema,
  erpPurchaseReceiptSchema,
  erpSupplierInvoiceListSchema,
  erpSupplierInvoiceSchema,
  erpSupplierInvoiceDetailSchema,
  erpSupplierPaymentPreparationListSchema,
  erpSupplierPaymentPreparationSchema,
  erpQuoteListSchema,
  erpQuoteSchema,
  erpReminderPageSchema,
  erpReminderScanResultSchema,
  erpReminderSchema,
  erpTierListSchema,
  erpTierSchema,
  uuidSchema,
  type ErpMarocRouteId,
} from 'twenty-shared/erp-maroc';
import { z, type ZodType } from 'zod';

export type ErpMarocHttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
export type ErpMarocRouteKind = 'json' | 'pdf';
export type ErpMarocIdempotencyPolicy = 'forbidden' | 'required';
export type ErpMarocQuery = Readonly<Record<string, unknown>> | URLSearchParams;

export type ErpMarocRoute = Readonly<{
  routeId: ErpMarocRouteId;
  method: ErpMarocHttpMethod;
  pattern: RegExp;
  build: (match: RegExpMatchArray) => string;
  queryKeys: readonly string[];
  responseSchema: ZodType;
  kind: ErpMarocRouteKind;
  idempotency: ErpMarocIdempotencyPolicy;
}>;

export type ResolvedErpMarocRoute = Readonly<{
  routeId: ErpMarocRouteId;
  method: ErpMarocHttpMethod;
  upstreamPath: string;
  responseSchema: ZodType;
  kind: ErpMarocRouteKind;
  idempotency: ErpMarocIdempotencyPolicy;
}>;

// Capture one safe path segment, then delegate UUID semantics to the shared schema.
const uuidSource = '([^/]+)';
const noQuery = Object.freeze([] as string[]);
const pageQuery = Object.freeze(['cursor', 'limit']);
const paymentQuery = Object.freeze([
  'status',
  'kind',
  'method',
  'tierId',
  'invoiceId',
  'from',
  'to',
  'cursor',
  'limit',
]);
const chequeQuery = Object.freeze([
  'direction',
  'instrumentType',
  'status',
  'bankAccountId',
  'tierId',
  'dueBefore',
  'search',
  'cursor',
  'limit',
]);
const chequeAlertQuery = Object.freeze([
  'horizonDays',
  'staleDepositDays',
  'lowBookThreshold',
]);
const chequeEligibleQuery = Object.freeze(['bankAccountId']);
const creditNoteQuery = Object.freeze([
  'status',
  'tierId',
  'invoiceId',
  'from',
  'to',
  'cursor',
  'limit',
]);
const reminderQuery = Object.freeze(['status', 'level', 'cursor', 'limit']);
const accountingEntryQuery = Object.freeze([
  'status',
  'sourceType',
  'from',
  'to',
  'cursor',
  'limit',
]);
const accountingProvisionQuery = Object.freeze(['status', 'exerciceId']);
const accountingReportQuery = Object.freeze(['from', 'to', 'includeDraft']);
const grandLivreQuery = Object.freeze([
  'accountCode',
  ...accountingReportQuery,
]);
const lettrageQuery = Object.freeze(['accountCode']);
const documentQuery = Object.freeze(['search', 'type', 'tag']);
const fiscalExerciseQuery = Object.freeze(['exerciceId']);
const fiscalAdc080fQuery = Object.freeze(['regime']);
const fiscalDeadlineSeedQuery = Object.freeze(['year']);
const liasseExportQuery = Object.freeze(['format']);
const accountingReviewExportQuery = Object.freeze(['format']);
const pdfSchema = z.instanceof(Uint8Array);

const exact = (path: string) => new RegExp(`^${path}$`);
const detail = (collection: string) =>
  new RegExp(`^/${collection}/${uuidSource}$`);
const action = (collection: string, actionName: string) =>
  new RegExp(`^/${collection}/${uuidSource}/${actionName}$`);

const staticBuilder = (path: string) => () => path;
const idBuilder =
  (builder: (id: string) => string) => (match: RegExpMatchArray) =>
    builder(uuidSchema.parse(match[1]));

const liasseTableCodeSchema = z.string().regex(/^[A-Z0-9_-]{1,20}$/);
const liasseRowCodeSchema = z.string().regex(/^[A-Z0-9_-]{1,80}$/);
const liasseTablePattern = new RegExp(
  `^/liasse/exercises/${uuidSource}/tables/([^/]+)$`,
);
const liasseRowPattern = new RegExp(
  `^/liasse/exercises/${uuidSource}/tables/([^/]+)/rows/([^/]+)$`,
);
const liasseTableBuilder = (match: RegExpMatchArray) =>
  erpMarocUpstreamRoutes.liasse.table(
    uuidSchema.parse(match[1]),
    liasseTableCodeSchema.parse(match[2]),
  );
const liasseRowBuilder = (match: RegExpMatchArray) =>
  erpMarocUpstreamRoutes.liasse.row(
    uuidSchema.parse(match[1]),
    liasseTableCodeSchema.parse(match[2]),
    liasseRowCodeSchema.parse(match[3]),
  );

const defineRoute = (route: ErpMarocRoute): ErpMarocRoute => {
  Object.freeze(route.pattern);

  return Object.freeze(route);
};

const routes: ErpMarocRoute[] = [
  defineRoute({
    routeId: erpMarocRouteIds.context,
    method: 'GET',
    pattern: exact('/context'),
    build: staticBuilder(erpMarocUpstreamRoutes.context),
    queryKeys: noQuery,
    responseSchema: erpContextSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.productsCollection,
    method: 'GET',
    pattern: exact('/products'),
    build: staticBuilder(erpMarocUpstreamRoutes.products.collection),
    queryKeys: noQuery,
    responseSchema: erpProductListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.productsCollection,
    method: 'POST',
    pattern: exact('/products'),
    build: staticBuilder(erpMarocUpstreamRoutes.products.collection),
    queryKeys: noQuery,
    responseSchema: erpProductSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.productDetail,
    method: 'GET',
    pattern: detail('products'),
    build: idBuilder(erpMarocUpstreamRoutes.products.detail),
    queryKeys: noQuery,
    responseSchema: erpProductSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.productDetail,
    method: 'PATCH',
    pattern: detail('products'),
    build: idBuilder(erpMarocUpstreamRoutes.products.detail),
    queryKeys: noQuery,
    responseSchema: erpProductSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.productDetail,
    method: 'DELETE',
    pattern: detail('products'),
    build: idBuilder(erpMarocUpstreamRoutes.products.detail),
    queryKeys: noQuery,
    responseSchema: erpProductSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.tiersCollection,
    method: 'GET',
    pattern: exact('/tiers'),
    build: staticBuilder(erpMarocUpstreamRoutes.tiers.collection),
    queryKeys: noQuery,
    responseSchema: erpTierListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.tiersCollection,
    method: 'POST',
    pattern: exact('/tiers'),
    build: staticBuilder(erpMarocUpstreamRoutes.tiers.collection),
    queryKeys: noQuery,
    responseSchema: erpTierSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.tiersSyncFromTwentyCompany,
    method: 'POST',
    pattern: exact('/tiers/sync-from-twenty-company'),
    build: staticBuilder(erpMarocUpstreamRoutes.tiers.syncFromTwentyCompany),
    queryKeys: noQuery,
    responseSchema: erpTierSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.tierDetail,
    method: 'GET',
    pattern: detail('tiers'),
    build: idBuilder(erpMarocUpstreamRoutes.tiers.detail),
    queryKeys: noQuery,
    responseSchema: erpTierSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.tierDetail,
    method: 'PATCH',
    pattern: detail('tiers'),
    build: idBuilder(erpMarocUpstreamRoutes.tiers.detail),
    queryKeys: noQuery,
    responseSchema: erpTierSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quotesCollection,
    method: 'GET',
    pattern: exact('/quotes'),
    build: staticBuilder(erpMarocUpstreamRoutes.quotes.collection),
    queryKeys: noQuery,
    responseSchema: erpQuoteListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quotesCollection,
    method: 'POST',
    pattern: exact('/quotes'),
    build: staticBuilder(erpMarocUpstreamRoutes.quotes.collection),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quotesFromOpportunity,
    method: 'POST',
    pattern: exact('/quotes/from-opportunity'),
    build: staticBuilder(erpMarocUpstreamRoutes.quotes.fromOpportunity),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quoteDetail,
    method: 'GET',
    pattern: detail('quotes'),
    build: idBuilder(erpMarocUpstreamRoutes.quotes.detail),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quoteDetail,
    method: 'PATCH',
    pattern: detail('quotes'),
    build: idBuilder(erpMarocUpstreamRoutes.quotes.detail),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quoteSend,
    method: 'POST',
    pattern: action('quotes', 'send'),
    build: idBuilder(erpMarocUpstreamRoutes.quotes.send),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quoteAccept,
    method: 'POST',
    pattern: action('quotes', 'accept'),
    build: idBuilder(erpMarocUpstreamRoutes.quotes.accept),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.quoteReject,
    method: 'POST',
    pattern: action('quotes', 'reject'),
    build: idBuilder(erpMarocUpstreamRoutes.quotes.reject),
    queryKeys: noQuery,
    responseSchema: erpQuoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrdersCollection,
    method: 'GET',
    pattern: exact('/purchase-orders'),
    build: staticBuilder(erpMarocUpstreamRoutes.purchaseOrders.collection),
    queryKeys: noQuery,
    responseSchema: erpPurchaseOrderListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrdersCollection,
    method: 'POST',
    pattern: exact('/purchase-orders'),
    build: staticBuilder(erpMarocUpstreamRoutes.purchaseOrders.collection),
    queryKeys: noQuery,
    responseSchema: erpPurchaseOrderSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderDetail,
    method: 'GET',
    pattern: detail('purchase-orders'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.detail),
    queryKeys: noQuery,
    responseSchema: erpPurchaseOrderSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderConfirm,
    method: 'POST',
    pattern: action('purchase-orders', 'confirm'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.confirm),
    queryKeys: noQuery,
    responseSchema: erpPurchaseOrderSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderCancel,
    method: 'POST',
    pattern: action('purchase-orders', 'cancel'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.cancel),
    queryKeys: noQuery,
    responseSchema: erpPurchaseOrderSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderReceipts,
    method: 'GET',
    pattern: action('purchase-orders', 'receipts'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.receipts),
    queryKeys: noQuery,
    responseSchema: erpPurchaseReceiptListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierInvoiceDetail,
    method: 'GET',
    pattern: detail('supplier-invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.supplierInvoices.detail),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceDetailSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierInvoiceDetail,
    method: 'PATCH',
    pattern: detail('supplier-invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.supplierInvoices.detail),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceDetailSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierInvoiceApprove,
    method: 'POST',
    pattern: action('supplier-invoices', 'approve'),
    build: idBuilder(erpMarocUpstreamRoutes.supplierInvoices.approve),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceDetailSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierInvoiceCancel,
    method: 'POST',
    pattern: action('supplier-invoices', 'cancel'),
    build: idBuilder(erpMarocUpstreamRoutes.supplierInvoices.cancel),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceDetailSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierInvoicePaymentPreparations,
    method: 'GET',
    pattern: new RegExp(
      `^/supplier-invoices/${uuidSource}/payment-preparations$`,
    ),
    build: idBuilder(
      erpMarocUpstreamRoutes.supplierInvoices.paymentPreparations,
    ),
    queryKeys: noQuery,
    responseSchema: erpSupplierPaymentPreparationListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierInvoicePaymentPreparations,
    method: 'POST',
    pattern: new RegExp(
      `^/supplier-invoices/${uuidSource}/payment-preparations$`,
    ),
    build: idBuilder(
      erpMarocUpstreamRoutes.supplierInvoices.paymentPreparations,
    ),
    queryKeys: noQuery,
    responseSchema: erpSupplierPaymentPreparationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.supplierPaymentPreparationCancel,
    method: 'POST',
    pattern: action('supplier-payment-preparations', 'cancel'),
    build: idBuilder(erpMarocUpstreamRoutes.supplierPaymentPreparations.cancel),
    queryKeys: noQuery,
    responseSchema: erpSupplierPaymentPreparationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderSupplierInvoices,
    method: 'GET',
    pattern: action('purchase-orders', 'supplier-invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.supplierInvoices),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderSupplierInvoices,
    method: 'POST',
    pattern: action('purchase-orders', 'supplier-invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.supplierInvoices),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.purchaseOrderReceipts,
    method: 'POST',
    pattern: action('purchase-orders', 'receipts'),
    build: idBuilder(erpMarocUpstreamRoutes.purchaseOrders.receipts),
    queryKeys: noQuery,
    responseSchema: erpPurchaseReceiptSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoicesCollection,
    method: 'GET',
    pattern: exact('/invoices'),
    build: staticBuilder(erpMarocUpstreamRoutes.invoices.collection),
    queryKeys: pageQuery,
    responseSchema: erpInvoicePageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoicesCollection,
    method: 'POST',
    pattern: exact('/invoices'),
    build: staticBuilder(erpMarocUpstreamRoutes.invoices.collection),
    queryKeys: noQuery,
    responseSchema: erpInvoiceSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoiceFromQuote,
    method: 'POST',
    pattern: new RegExp(`^/invoices/from-quote/${uuidSource}$`),
    build: idBuilder(erpMarocUpstreamRoutes.invoices.fromQuote),
    queryKeys: noQuery,
    responseSchema: erpInvoiceSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoiceDetail,
    method: 'GET',
    pattern: detail('invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.invoices.detail),
    queryKeys: noQuery,
    responseSchema: erpInvoiceReadSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoiceDetail,
    method: 'PATCH',
    pattern: detail('invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.invoices.detail),
    queryKeys: noQuery,
    responseSchema: erpInvoiceSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoiceValidate,
    method: 'POST',
    pattern: action('invoices', 'validate'),
    build: idBuilder(erpMarocUpstreamRoutes.invoices.validate),
    queryKeys: noQuery,
    responseSchema: erpInvoiceSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoiceSend,
    method: 'POST',
    pattern: action('invoices', 'send'),
    build: idBuilder(erpMarocUpstreamRoutes.invoices.send),
    queryKeys: noQuery,
    responseSchema: erpInvoiceSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.invoicePdf,
    method: 'GET',
    pattern: action('invoices', 'pdf'),
    build: idBuilder(erpMarocUpstreamRoutes.invoices.pdf),
    queryKeys: noQuery,
    responseSchema: pdfSchema,
    kind: 'pdf',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.paymentsCollection,
    method: 'GET',
    pattern: exact('/payments'),
    build: staticBuilder(erpMarocUpstreamRoutes.payments.collection),
    queryKeys: paymentQuery,
    responseSchema: erpPaymentPageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.paymentsCollection,
    method: 'POST',
    pattern: exact('/payments'),
    build: staticBuilder(erpMarocUpstreamRoutes.payments.collection),
    queryKeys: noQuery,
    responseSchema: erpPaymentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.paymentDetail,
    method: 'GET',
    pattern: detail('payments'),
    build: idBuilder(erpMarocUpstreamRoutes.payments.detail),
    queryKeys: noQuery,
    responseSchema: erpPaymentSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.paymentEligibleInvoices,
    method: 'GET',
    pattern: action('payments', 'eligible-invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.payments.eligibleInvoices),
    queryKeys: pageQuery,
    responseSchema: erpEligibleInvoicePageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.paymentAllocate,
    method: 'POST',
    pattern: action('payments', 'allocate'),
    build: idBuilder(erpMarocUpstreamRoutes.payments.allocate),
    queryKeys: noQuery,
    responseSchema: erpPaymentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.paymentTerminate,
    method: 'POST',
    pattern: action('payments', 'terminate'),
    build: idBuilder(erpMarocUpstreamRoutes.payments.terminate),
    queryKeys: noQuery,
    responseSchema: erpPaymentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeBooks,
    method: 'GET',
    pattern: exact('/cheques/books'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.books),
    queryKeys: noQuery,
    responseSchema: erpChequeBookListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeBooks,
    method: 'POST',
    pattern: exact('/cheques/books'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.books),
    queryKeys: noQuery,
    responseSchema: erpChequeBookSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeSummary,
    method: 'GET',
    pattern: exact('/cheques/summary'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.summary),
    queryKeys: noQuery,
    responseSchema: erpChequeSummarySchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeAlerts,
    method: 'GET',
    pattern: exact('/cheques/alerts'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.alerts),
    queryKeys: chequeAlertQuery,
    responseSchema: erpChequeAlertsSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeDepositSlipEligible,
    method: 'GET',
    pattern: exact('/cheques/deposit-slips/eligible'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.depositSlipEligible),
    queryKeys: chequeEligibleQuery,
    responseSchema: erpChequeDepositEligibleListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeDepositSlips,
    method: 'GET',
    pattern: exact('/cheques/deposit-slips'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.depositSlips),
    queryKeys: noQuery,
    responseSchema: erpChequeDepositSlipListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeDepositSlips,
    method: 'POST',
    pattern: exact('/cheques/deposit-slips'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.depositSlips),
    queryKeys: noQuery,
    responseSchema: erpChequeDepositSlipSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeDepositSlipPdf,
    method: 'GET',
    pattern: new RegExp(`^/cheques/deposit-slips/${uuidSource}/pdf$`),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.depositSlipPdf),
    queryKeys: noQuery,
    responseSchema: pdfSchema,
    kind: 'pdf',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeDepositSlipDetail,
    method: 'GET',
    pattern: new RegExp(`^/cheques/deposit-slips/${uuidSource}$`),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.depositSlipDetail),
    queryKeys: noQuery,
    responseSchema: erpChequeDepositSlipSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequesCollection,
    method: 'GET',
    pattern: exact('/cheques'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.collection),
    queryKeys: chequeQuery,
    responseSchema: erpChequePageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequesCollection,
    method: 'POST',
    pattern: exact('/cheques'),
    build: staticBuilder(erpMarocUpstreamRoutes.cheques.collection),
    queryKeys: noQuery,
    responseSchema: erpChequeSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeReconciliationCandidates,
    method: 'GET',
    pattern: action('cheques', 'reconciliation-candidates'),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.reconciliationCandidates),
    queryKeys: noQuery,
    responseSchema: erpChequeReconciliationCandidatesSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeReconcile,
    method: 'POST',
    pattern: action('cheques', 'reconcile'),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.reconcile),
    queryKeys: noQuery,
    responseSchema: erpChequeSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeUnreconcile,
    method: 'POST',
    pattern: action('cheques', 'unreconcile'),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.unreconcile),
    queryKeys: noQuery,
    responseSchema: erpChequeSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeTransition,
    method: 'POST',
    pattern: action('cheques', 'transition'),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.transition),
    queryKeys: noQuery,
    responseSchema: erpChequeSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.chequeDetail,
    method: 'GET',
    pattern: detail('cheques'),
    build: idBuilder(erpMarocUpstreamRoutes.cheques.detail),
    queryKeys: noQuery,
    responseSchema: erpChequeSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNotesCollection,
    method: 'GET',
    pattern: exact('/credit-notes'),
    build: staticBuilder(erpMarocUpstreamRoutes.creditNotes.collection),
    queryKeys: creditNoteQuery,
    responseSchema: erpCreditNotePageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNotesCollection,
    method: 'POST',
    pattern: exact('/credit-notes'),
    build: staticBuilder(erpMarocUpstreamRoutes.creditNotes.collection),
    queryKeys: noQuery,
    responseSchema: erpCreditNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNoteDetail,
    method: 'GET',
    pattern: detail('credit-notes'),
    build: idBuilder(erpMarocUpstreamRoutes.creditNotes.detail),
    queryKeys: noQuery,
    responseSchema: erpCreditNoteSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNoteDetail,
    method: 'PATCH',
    pattern: detail('credit-notes'),
    build: idBuilder(erpMarocUpstreamRoutes.creditNotes.detail),
    queryKeys: noQuery,
    responseSchema: erpCreditNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNoteValidate,
    method: 'POST',
    pattern: action('credit-notes', 'validate'),
    build: idBuilder(erpMarocUpstreamRoutes.creditNotes.validate),
    queryKeys: noQuery,
    responseSchema: erpCreditNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNoteEligibleInvoices,
    method: 'GET',
    pattern: action('credit-notes', 'eligible-invoices'),
    build: idBuilder(erpMarocUpstreamRoutes.creditNotes.eligibleInvoices),
    queryKeys: pageQuery,
    responseSchema: erpEligibleInvoicePageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNoteAllocate,
    method: 'POST',
    pattern: action('credit-notes', 'allocate'),
    build: idBuilder(erpMarocUpstreamRoutes.creditNotes.allocate),
    queryKeys: noQuery,
    responseSchema: erpCreditNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.creditNoteCancel,
    method: 'POST',
    pattern: action('credit-notes', 'cancel'),
    build: idBuilder(erpMarocUpstreamRoutes.creditNotes.cancel),
    queryKeys: noQuery,
    responseSchema: erpCreditNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntriesCollection,
    method: 'GET',
    pattern: exact('/accounting/entries'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.entries),
    queryKeys: accountingEntryQuery,
    responseSchema: erpAccountingEntryPageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntriesCollection,
    method: 'POST',
    pattern: exact('/accounting/entries'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.entries),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntryDetail,
    method: 'GET',
    pattern: detail('accounting/entries'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.detail),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntryDetail,
    method: 'PATCH',
    pattern: detail('accounting/entries'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.detail),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntryDuplicate,
    method: 'POST',
    pattern: action('accounting/entries', 'duplicate'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.duplicate),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntryValidate,
    method: 'POST',
    pattern: action('accounting/entries', 'validate'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.validate),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntryReject,
    method: 'POST',
    pattern: action('accounting/entries', 'reject'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.reject),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingEntryReverse,
    method: 'POST',
    pattern: action('accounting/entries', 'reverse'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.reverse),
    queryKeys: noQuery,
    responseSchema: erpAccountingEntrySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionsCollection,
    method: 'GET',
    pattern: exact('/accounting/provisions'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.provisions),
    queryKeys: accountingProvisionQuery,
    responseSchema: erpAccountingProvisionListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionsCollection,
    method: 'POST',
    pattern: exact('/accounting/provisions'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.provisions),
    queryKeys: noQuery,
    responseSchema: erpAccountingProvisionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionDetail,
    method: 'GET',
    pattern: detail('accounting/provisions'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.provision),
    queryKeys: noQuery,
    responseSchema: erpAccountingProvisionSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionDetail,
    method: 'PATCH',
    pattern: detail('accounting/provisions'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.provision),
    queryKeys: noQuery,
    responseSchema: erpAccountingProvisionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionPost,
    method: 'POST',
    pattern: action('accounting/provisions', 'post'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.postProvision),
    queryKeys: noQuery,
    responseSchema: erpAccountingProvisionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionReverse,
    method: 'POST',
    pattern: action('accounting/provisions', 'reverse'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.reverseProvision),
    queryKeys: noQuery,
    responseSchema: erpAccountingProvisionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingProvisionCancel,
    method: 'POST',
    pattern: action('accounting/provisions', 'cancel'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.cancelProvision),
    queryKeys: noQuery,
    responseSchema: erpAccountingProvisionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingReferences,
    method: 'GET',
    pattern: exact('/accounting/references'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.references),
    queryKeys: noQuery,
    responseSchema: erpAccountingReferencesSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingAccountsCollection,
    method: 'POST',
    pattern: exact('/accounting/references/accounts'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.accounts),
    queryKeys: noQuery,
    responseSchema: erpAccountingAccountSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingAccountDetail,
    method: 'PATCH',
    pattern: detail('accounting/references/accounts'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.account),
    queryKeys: noQuery,
    responseSchema: erpAccountingAccountSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingJournalsCollection,
    method: 'POST',
    pattern: exact('/accounting/references/journals'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.journals),
    queryKeys: noQuery,
    responseSchema: erpAccountingJournalSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingJournalDetail,
    method: 'PATCH',
    pattern: detail('accounting/references/journals'),
    build: idBuilder(erpMarocUpstreamRoutes.accounting.journal),
    queryKeys: noQuery,
    responseSchema: erpAccountingJournalSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingGrandLivre,
    method: 'GET',
    pattern: exact('/accounting/grand-livre'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.grandLivre),
    queryKeys: grandLivreQuery,
    responseSchema: erpGrandLivreReportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingBalance,
    method: 'GET',
    pattern: exact('/accounting/balance'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.balance),
    queryKeys: accountingReportQuery,
    responseSchema: erpBalanceReportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarations,
    method: 'GET',
    pattern: exact('/fiscal/declarations'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.declarations),
    queryKeys: noQuery,
    responseSchema: erpTaxDeclarationListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentsCollection,
    method: 'GET',
    pattern: exact('/documents'),
    build: staticBuilder(erpMarocUpstreamRoutes.documents.collection),
    queryKeys: documentQuery,
    responseSchema: erpDocumentListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentsCollection,
    method: 'POST',
    pattern: exact('/documents'),
    build: staticBuilder(erpMarocUpstreamRoutes.documents.collection),
    queryKeys: noQuery,
    responseSchema: erpDocumentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentDetail,
    method: 'GET',
    pattern: detail('documents'),
    build: idBuilder(erpMarocUpstreamRoutes.documents.detail),
    queryKeys: noQuery,
    responseSchema: erpDocumentSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentContent,
    method: 'GET',
    pattern: action('documents', 'content'),
    build: idBuilder(erpMarocUpstreamRoutes.documents.content),
    queryKeys: noQuery,
    responseSchema: erpDocumentContentSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentOcrRetry,
    method: 'POST',
    pattern: new RegExp(`^/documents/${uuidSource}/ocr/retry$`),
    build: idBuilder(erpMarocUpstreamRoutes.documents.retryOcr),
    queryKeys: noQuery,
    responseSchema: erpDocumentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentOcrValidate,
    method: 'POST',
    pattern: new RegExp(`^/documents/${uuidSource}/ocr/validate$`),
    build: idBuilder(erpMarocUpstreamRoutes.documents.validateOcr),
    queryKeys: noQuery,
    responseSchema: erpDocumentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.documentCreateSupplierInvoice,
    method: 'POST',
    pattern: action('documents', 'create-supplier-invoice'),
    build: idBuilder(erpMarocUpstreamRoutes.documents.createSupplierInvoice),
    queryKeys: noQuery,
    responseSchema: erpSupplierInvoiceSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.expenseNotes,
    method: 'GET',
    pattern: exact('/operations/expense-notes'),
    build: staticBuilder(erpMarocUpstreamRoutes.operations.expenseNotes),
    queryKeys: noQuery,
    responseSchema: erpExpenseNoteListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.expenseNotes,
    method: 'POST',
    pattern: exact('/operations/expense-notes'),
    build: staticBuilder(erpMarocUpstreamRoutes.operations.expenseNotes),
    queryKeys: noQuery,
    responseSchema: erpExpenseNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.expenseNoteSubmit,
    method: 'POST',
    pattern: action('operations/expense-notes', 'submit'),
    build: idBuilder(erpMarocUpstreamRoutes.operations.submitExpenseNote),
    queryKeys: noQuery,
    responseSchema: erpExpenseNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.expenseNoteDecision,
    method: 'PATCH',
    pattern: action('operations/expense-notes', 'decision'),
    build: idBuilder(erpMarocUpstreamRoutes.operations.decideExpenseNote),
    queryKeys: noQuery,
    responseSchema: erpExpenseNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.expenseNotePayment,
    method: 'POST',
    pattern: action('operations/expense-notes', 'pay'),
    build: idBuilder(erpMarocUpstreamRoutes.operations.payExpenseNote),
    queryKeys: noQuery,
    responseSchema: erpExpenseNoteSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalTvaCalculate,
    method: 'POST',
    pattern: exact('/fiscal/tva/calculate'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.calculateTva),
    queryKeys: noQuery,
    responseSchema: erpTaxDeclarationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalTvaProrata,
    method: 'GET',
    pattern: exact('/fiscal/tva/prorata'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.tvaProrata),
    queryKeys: fiscalExerciseQuery,
    responseSchema: erpTvaProrataPeriodListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalTvaProrataCalculate,
    method: 'POST',
    pattern: exact('/fiscal/tva/prorata/calculate'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.calculateTvaProrata),
    queryKeys: noQuery,
    responseSchema: erpTvaProrataPeriodSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalTvaProrataAnnual,
    method: 'GET',
    pattern: exact('/fiscal/tva/prorata/annual'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.annualTvaProrata),
    queryKeys: fiscalExerciseQuery,
    responseSchema: erpAnnualTvaProrataSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalTvaProrataAnnualPost,
    method: 'POST',
    pattern: exact('/fiscal/tva/prorata/annual/post'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.postAnnualTvaProrata),
    queryKeys: noQuery,
    responseSchema: erpTvaProrataPostingSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalIsCalculate,
    method: 'POST',
    pattern: exact('/fiscal/is/calculate'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.calculateIs),
    queryKeys: noQuery,
    responseSchema: erpTaxDeclarationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationStatus,
    method: 'PATCH',
    pattern: action('fiscal/declarations', 'status'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.declarationStatus),
    queryKeys: noQuery,
    responseSchema: erpTaxDeclarationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationSimpl,
    method: 'GET',
    pattern: action('fiscal/declarations', 'simpl'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.declarationSimpl),
    queryKeys: noQuery,
    responseSchema: erpFileExportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationAdc080f,
    method: 'GET',
    pattern: action('fiscal/declarations', 'adc080f'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.declarationAdc080f),
    queryKeys: fiscalAdc080fQuery,
    responseSchema: erpFileExportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationIsXml,
    method: 'GET',
    pattern: action('fiscal/declarations', 'is-xml'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.declarationIsXml),
    queryKeys: noQuery,
    responseSchema: erpFileExportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationPayments,
    method: 'GET',
    pattern: action('fiscal/declarations', 'payments'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.declarationPayments),
    queryKeys: noQuery,
    responseSchema: erpTaxPaymentListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationPaymentCandidates,
    method: 'GET',
    pattern: action('fiscal/declarations', 'payment-candidates'),
    build: idBuilder(
      erpMarocUpstreamRoutes.fiscal.declarationPaymentCandidates,
    ),
    queryKeys: noQuery,
    responseSchema: erpTaxPaymentCandidateListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeclarationPayments,
    method: 'POST',
    pattern: action('fiscal/declarations', 'payments'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.declarationPayments),
    queryKeys: noQuery,
    responseSchema: erpTaxPaymentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeadlines,
    method: 'GET',
    pattern: exact('/fiscal/deadlines'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.deadlines),
    queryKeys: noQuery,
    responseSchema: erpFiscalDeadlineListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeadlinesSeed,
    method: 'POST',
    pattern: exact('/fiscal/deadlines/seed'),
    build: staticBuilder(erpMarocUpstreamRoutes.fiscal.seedDeadlines),
    queryKeys: fiscalDeadlineSeedQuery,
    responseSchema: erpFiscalDeadlineListSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.fiscalDeadlineComplete,
    method: 'PATCH',
    pattern: action('fiscal/deadlines', 'complete'),
    build: idBuilder(erpMarocUpstreamRoutes.fiscal.completeDeadline),
    queryKeys: noQuery,
    responseSchema: erpFiscalDeadlineSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExercises,
    method: 'GET',
    pattern: exact('/accounting-compliance/exercises'),
    build: staticBuilder(erpMarocUpstreamRoutes.compliance.exercises),
    queryKeys: noQuery,
    responseSchema: erpExerciseListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExercises,
    method: 'POST',
    pattern: exact('/accounting-compliance/exercises'),
    build: staticBuilder(erpMarocUpstreamRoutes.compliance.exercises),
    queryKeys: noQuery,
    responseSchema: erpExerciseSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseReview,
    method: 'POST',
    pattern: action('accounting-compliance/exercises', 'review'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.initializeReview),
    queryKeys: noQuery,
    responseSchema: erpAccountingReviewTaskListSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseReviewDossier,
    method: 'GET',
    pattern: action('accounting-compliance/exercises', 'review-dossier'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.reviewDossier),
    queryKeys: noQuery,
    responseSchema: erpAccountingReviewDossierSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseReviewRefresh,
    method: 'POST',
    pattern: action('accounting-compliance/exercises', 'review-refresh'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.refreshReview),
    queryKeys: noQuery,
    responseSchema: erpAccountingReviewDossierSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseReviewExport,
    method: 'GET',
    pattern: action('accounting-compliance/exercises', 'review-export'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.exportReview),
    queryKeys: accountingReviewExportQuery,
    responseSchema: erpAccountingReviewExportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceReviewTask,
    method: 'PATCH',
    pattern: detail('accounting-compliance/review-tasks'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.reviewTask),
    queryKeys: noQuery,
    responseSchema: erpAccountingReviewTaskSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceReviewTaskDecision,
    method: 'POST',
    pattern: action('accounting-compliance/review-tasks', 'decision'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.reviewTaskDecision),
    queryKeys: noQuery,
    responseSchema: erpAccountingReviewTaskSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceReviewAccount,
    method: 'PATCH',
    pattern: detail('accounting-compliance/review-accounts'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.reviewAccount),
    queryKeys: noQuery,
    responseSchema: erpAccountingReviewAccountSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.compliancePeriodClose,
    method: 'POST',
    pattern: action('accounting-compliance/periods', 'close'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.closePeriod),
    queryKeys: noQuery,
    responseSchema: erpAccountingPeriodSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.compliancePeriodReopen,
    method: 'POST',
    pattern: action('accounting-compliance/periods', 'reopen'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.reopenPeriod),
    queryKeys: noQuery,
    responseSchema: erpAccountingPeriodSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseClose,
    method: 'POST',
    pattern: action('accounting-compliance/exercises', 'close'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.closeExercise),
    queryKeys: noQuery,
    responseSchema: erpExerciseClosingResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseStatements,
    method: 'GET',
    pattern: action('accounting-compliance/exercises', 'statements'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.statements),
    queryKeys: noQuery,
    responseSchema: erpFinancialStatementsSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceExerciseFec,
    method: 'GET',
    pattern: action('accounting-compliance/exercises', 'fec'),
    build: idBuilder(erpMarocUpstreamRoutes.compliance.fec),
    queryKeys: noQuery,
    responseSchema: erpFecExportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.complianceFecImport,
    method: 'POST',
    pattern: exact('/accounting-compliance/fec/import'),
    build: staticBuilder(erpMarocUpstreamRoutes.compliance.importFec),
    queryKeys: noQuery,
    responseSchema: erpFecImportResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.liasseTables,
    method: 'GET',
    pattern: new RegExp(`^/liasse/exercises/${uuidSource}/tables$`),
    build: idBuilder(erpMarocUpstreamRoutes.liasse.tables),
    queryKeys: noQuery,
    responseSchema: erpLiasseTableSummaryListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.liasseValidation,
    method: 'GET',
    pattern: new RegExp(`^/liasse/exercises/${uuidSource}/validation$`),
    build: idBuilder(erpMarocUpstreamRoutes.liasse.validation),
    queryKeys: noQuery,
    responseSchema: erpLiasseValidationSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.liasseTable,
    method: 'GET',
    pattern: liasseTablePattern,
    build: liasseTableBuilder,
    queryKeys: noQuery,
    responseSchema: erpLiasseTableDetailSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.liasseRow,
    method: 'PUT',
    pattern: liasseRowPattern,
    build: liasseRowBuilder,
    queryKeys: noQuery,
    responseSchema: erpLiasseRowSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.liasseRow,
    method: 'DELETE',
    pattern: liasseRowPattern,
    build: liasseRowBuilder,
    queryKeys: noQuery,
    responseSchema: erpLiasseDeleteResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.liasseExport,
    method: 'GET',
    pattern: new RegExp(`^/liasse/exercises/${uuidSource}/export$`),
    build: idBuilder(erpMarocUpstreamRoutes.liasse.export),
    queryKeys: liasseExportQuery,
    responseSchema: erpLiasseExportSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.regulatorySubmissions,
    method: 'GET',
    pattern: exact('/liasse/submissions'),
    build: staticBuilder(erpMarocUpstreamRoutes.liasse.submissions),
    queryKeys: noQuery,
    responseSchema: erpRegulatorySubmissionListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.regulatorySubmissionValidation,
    method: 'PATCH',
    pattern: action('liasse/submissions', 'external-validation'),
    build: idBuilder(erpMarocUpstreamRoutes.liasse.validateSubmission),
    queryKeys: noQuery,
    responseSchema: erpRegulatorySubmissionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingLettrageSuggestions,
    method: 'GET',
    pattern: exact('/accounting/lettrage/suggestions'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.lettrageSuggestions),
    queryKeys: lettrageQuery,
    responseSchema: erpLettrageSuggestionsSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingLettrageMatch,
    method: 'POST',
    pattern: exact('/accounting/lettrage/match'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.lettrageMatch),
    queryKeys: noQuery,
    responseSchema: erpLettrageMatchSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.accountingLettrageUnmatch,
    method: 'POST',
    pattern: exact('/accounting/lettrage/unmatch'),
    build: staticBuilder(erpMarocUpstreamRoutes.accounting.lettrageUnmatch),
    queryKeys: noQuery,
    responseSchema: erpLettrageMatchSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.remindersCollection,
    method: 'GET',
    pattern: exact('/reminders'),
    build: staticBuilder(erpMarocUpstreamRoutes.reminders.collection),
    queryKeys: reminderQuery,
    responseSchema: erpReminderPageSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.remindersScan,
    method: 'POST',
    pattern: exact('/reminders/scan'),
    build: staticBuilder(erpMarocUpstreamRoutes.reminders.scan),
    queryKeys: noQuery,
    responseSchema: erpReminderScanResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.reminderDetail,
    method: 'GET',
    pattern: detail('reminders'),
    build: idBuilder(erpMarocUpstreamRoutes.reminders.detail),
    queryKeys: noQuery,
    responseSchema: erpReminderSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.reminderApprove,
    method: 'POST',
    pattern: action('reminders', 'approve'),
    build: idBuilder(erpMarocUpstreamRoutes.reminders.approve),
    queryKeys: noQuery,
    responseSchema: erpReminderSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.reminderCancel,
    method: 'POST',
    pattern: action('reminders', 'cancel'),
    build: idBuilder(erpMarocUpstreamRoutes.reminders.cancel),
    queryKeys: noQuery,
    responseSchema: erpReminderSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingOverview,
    method: 'GET',
    pattern: exact('/marketing/overview'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.overview),
    queryKeys: noQuery,
    responseSchema: marketingOverviewSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingContactsCollection,
    method: 'GET',
    pattern: exact('/marketing/contacts'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.contacts),
    queryKeys: noQuery,
    responseSchema: marketingContactListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingContactsImportTiers,
    method: 'POST',
    pattern: exact('/marketing/contacts/import-tiers'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.importTiers),
    queryKeys: noQuery,
    responseSchema: marketingTierImportResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingContactConsent,
    method: 'POST',
    pattern: action('marketing/contacts', 'consent'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.contactConsent),
    queryKeys: noQuery,
    responseSchema: marketingContactSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingSegmentsCollection,
    method: 'GET',
    pattern: exact('/marketing/segments'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.segments),
    queryKeys: noQuery,
    responseSchema: marketingSegmentListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingSegmentsCollection,
    method: 'POST',
    pattern: exact('/marketing/segments'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.segments),
    queryKeys: noQuery,
    responseSchema: marketingSegmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingSegmentSync,
    method: 'POST',
    pattern: action('marketing/segments', 'sync'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.segmentSync),
    queryKeys: noQuery,
    responseSchema: marketingSegmentSyncResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingCampaignsCollection,
    method: 'GET',
    pattern: exact('/marketing/campaigns'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.campaigns),
    queryKeys: noQuery,
    responseSchema: marketingCampaignListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingCampaignsCollection,
    method: 'POST',
    pattern: exact('/marketing/campaigns'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.campaigns),
    queryKeys: noQuery,
    responseSchema: marketingCampaignSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingCampaignSend,
    method: 'POST',
    pattern: action('marketing/campaigns', 'send'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.campaignSend),
    queryKeys: noQuery,
    responseSchema: marketingCampaignSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingCampaignRefresh,
    method: 'POST',
    pattern: action('marketing/campaigns', 'refresh'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.campaignRefresh),
    queryKeys: noQuery,
    responseSchema: marketingCampaignSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingAutomationsCollection,
    method: 'GET',
    pattern: exact('/marketing/automations'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.automations),
    queryKeys: noQuery,
    responseSchema: marketingAutomationListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingAutomationsCollection,
    method: 'POST',
    pattern: exact('/marketing/automations'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.automations),
    queryKeys: noQuery,
    responseSchema: marketingAutomationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingAutomationActivate,
    method: 'POST',
    pattern: action('marketing/automations', 'activate'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.automationActivate),
    queryKeys: noQuery,
    responseSchema: marketingAutomationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingAutomationPause,
    method: 'POST',
    pattern: action('marketing/automations', 'pause'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.automationPause),
    queryKeys: noQuery,
    responseSchema: marketingAutomationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingScoringRulesCollection,
    method: 'GET',
    pattern: exact('/marketing/scoring-rules'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.scoringRules),
    queryKeys: noQuery,
    responseSchema: marketingScoringRuleListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingScoringRulesCollection,
    method: 'POST',
    pattern: exact('/marketing/scoring-rules'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.scoringRules),
    queryKeys: noQuery,
    responseSchema: marketingScoringRuleSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingScoringRuleToggle,
    method: 'POST',
    pattern: action('marketing/scoring-rules', 'toggle'),
    build: idBuilder(erpMarocUpstreamRoutes.marketing.scoringRuleToggle),
    queryKeys: noQuery,
    responseSchema: marketingScoringRuleSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingEventsCollection,
    method: 'GET',
    pattern: exact('/marketing/events'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.events),
    queryKeys: noQuery,
    responseSchema: marketingEventListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.marketingEventsCollection,
    method: 'POST',
    pattern: exact('/marketing/events'),
    build: staticBuilder(erpMarocUpstreamRoutes.marketing.events),
    queryKeys: noQuery,
    responseSchema: marketingEventSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.payrollRegulatorySummary,
    method: 'GET',
    pattern: exact('/payroll/regulatory/summary'),
    build: staticBuilder(erpMarocUpstreamRoutes.payroll.regulatorySummary),
    queryKeys: noQuery,
    responseSchema: payrollRegulatorySummarySchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.payrollRegulatoryRules,
    method: 'GET',
    pattern: exact('/payroll/regulatory/rules'),
    build: staticBuilder(erpMarocUpstreamRoutes.payroll.regulatoryRules),
    queryKeys: noQuery,
    responseSchema: payrollRuleListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.payrollRegulatoryComponents,
    method: 'GET',
    pattern: exact('/payroll/regulatory/components'),
    build: staticBuilder(erpMarocUpstreamRoutes.payroll.regulatoryComponents),
    queryKeys: noQuery,
    responseSchema: payrollComponentListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.payrollRegulatoryControls,
    method: 'GET',
    pattern: exact('/payroll/regulatory/controls'),
    build: staticBuilder(erpMarocUpstreamRoutes.payroll.regulatoryControls),
    queryKeys: noQuery,
    responseSchema: payrollControlDefinitionListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.payrollRegulatorySources,
    method: 'GET',
    pattern: exact('/payroll/regulatory/sources'),
    build: staticBuilder(erpMarocUpstreamRoutes.payroll.regulatorySources),
    queryKeys: noQuery,
    responseSchema: payrollLegalSourceListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.payrollRegulatorySeed,
    method: 'POST',
    pattern: exact('/payroll/regulatory/seed/morocco-2026'),
    build: staticBuilder(erpMarocUpstreamRoutes.payroll.regulatorySeed),
    queryKeys: noQuery,
    responseSchema: payrollRegulatorySeedResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrCoreSummary,
    method: 'GET',
    pattern: exact('/hr-core/summary'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.summary),
    queryKeys: noQuery,
    responseSchema: hrCoreSummarySchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrAccessMe,
    method: 'GET',
    pattern: exact('/hr-core/access/me'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.accessMe),
    queryKeys: noQuery,
    responseSchema: hrAccessContextSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrAccessAdministration,
    method: 'GET',
    pattern: exact('/hr-core/access/administration'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.accessAdministration),
    queryKeys: noQuery,
    responseSchema: hrAccessAdministrationSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrAccessGrants,
    method: 'POST',
    pattern: exact('/hr-core/access/grants'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.accessGrants),
    queryKeys: noQuery,
    responseSchema: hrAccessGrantSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEstablishments,
    method: 'GET',
    pattern: exact('/hr-core/establishments'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.establishments),
    queryKeys: noQuery,
    responseSchema: hrEstablishmentListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEstablishments,
    method: 'POST',
    pattern: exact('/hr-core/establishments'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.establishments),
    queryKeys: noQuery,
    responseSchema: hrEstablishmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEstablishmentDetail,
    method: 'PATCH',
    pattern: detail('hr-core/establishments'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.establishment),
    queryKeys: noQuery,
    responseSchema: hrEstablishmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrGrades,
    method: 'GET',
    pattern: exact('/hr-core/grades'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.grades),
    queryKeys: noQuery,
    responseSchema: hrGradeListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrGrades,
    method: 'POST',
    pattern: exact('/hr-core/grades'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.grades),
    queryKeys: noQuery,
    responseSchema: hrGradeSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrGradeDetail,
    method: 'PATCH',
    pattern: detail('hr-core/grades'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.grade),
    queryKeys: noQuery,
    responseSchema: hrGradeSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrCostCenters,
    method: 'GET',
    pattern: exact('/hr-core/cost-centers'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.costCenters),
    queryKeys: noQuery,
    responseSchema: hrCostCenterListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrCostCenters,
    method: 'POST',
    pattern: exact('/hr-core/cost-centers'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.costCenters),
    queryKeys: noQuery,
    responseSchema: hrCostCenterSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrCostCenterDetail,
    method: 'PATCH',
    pattern: detail('hr-core/cost-centers'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.costCenter),
    queryKeys: noQuery,
    responseSchema: hrCostCenterSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrTeams,
    method: 'GET',
    pattern: exact('/hr-core/teams'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.teams),
    queryKeys: noQuery,
    responseSchema: hrTeamListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrTeams,
    method: 'POST',
    pattern: exact('/hr-core/teams'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.teams),
    queryKeys: noQuery,
    responseSchema: hrTeamSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrTeamDetail,
    method: 'PATCH',
    pattern: detail('hr-core/teams'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.team),
    queryKeys: noQuery,
    responseSchema: hrTeamSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrWorkLocations,
    method: 'GET',
    pattern: exact('/hr-core/work-locations'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.workLocations),
    queryKeys: noQuery,
    responseSchema: hrWorkLocationListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrWorkLocations,
    method: 'POST',
    pattern: exact('/hr-core/work-locations'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.workLocations),
    queryKeys: noQuery,
    responseSchema: hrWorkLocationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrWorkLocationDetail,
    method: 'PATCH',
    pattern: detail('hr-core/work-locations'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.workLocation),
    queryKeys: noQuery,
    responseSchema: hrWorkLocationSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDepartments,
    method: 'GET',
    pattern: exact('/hr-core/departments'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.departments),
    queryKeys: noQuery,
    responseSchema: hrDepartmentListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDepartments,
    method: 'POST',
    pattern: exact('/hr-core/departments'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.departments),
    queryKeys: noQuery,
    responseSchema: hrDepartmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDepartmentDetail,
    method: 'PATCH',
    pattern: detail('hr-core/departments'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.department),
    queryKeys: noQuery,
    responseSchema: hrDepartmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrJobPositions,
    method: 'GET',
    pattern: exact('/hr-core/job-positions'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.jobPositions),
    queryKeys: noQuery,
    responseSchema: hrJobPositionListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrJobPositions,
    method: 'POST',
    pattern: exact('/hr-core/job-positions'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.jobPositions),
    queryKeys: noQuery,
    responseSchema: hrJobPositionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrJobPositionDetail,
    method: 'PATCH',
    pattern: detail('hr-core/job-positions'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.jobPosition),
    queryKeys: noQuery,
    responseSchema: hrJobPositionSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeImportTemplate,
    method: 'GET',
    pattern: exact('/hr-core/employee-import/template'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.employeeImportTemplate),
    queryKeys: noQuery,
    responseSchema: hrEmployeeImportTemplateSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeImportPreview,
    method: 'POST',
    pattern: exact('/hr-core/employee-import/preview'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.employeeImportPreview),
    queryKeys: noQuery,
    responseSchema: hrEmployeeImportPreviewSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeImportCommit,
    method: 'POST',
    pattern: exact('/hr-core/employee-import/commit'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.employeeImportCommit),
    queryKeys: noQuery,
    responseSchema: hrEmployeeImportCommitResultSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployees,
    method: 'GET',
    pattern: exact('/hr-core/employees'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.employees),
    queryKeys: noQuery,
    responseSchema: hrEmployeeListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeDetail,
    method: 'GET',
    pattern: detail('hr-core/employees'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employee),
    queryKeys: noQuery,
    responseSchema: hrEmployeeDetailSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeePersonalDetails,
    method: 'PATCH',
    pattern: action('hr-core/employees', 'personal-details'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeePersonalDetails),
    queryKeys: noQuery,
    responseSchema: hrEmployeePrivateProfileSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeDependants,
    method: 'POST',
    pattern: action('hr-core/employees', 'dependants'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeeDependants),
    queryKeys: noQuery,
    responseSchema: hrEmployeeDependantSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDependantDetail,
    method: 'PATCH',
    pattern: detail('hr-core/dependants'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.dependant),
    queryKeys: noQuery,
    responseSchema: hrEmployeeDependantSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeEmergencyContacts,
    method: 'POST',
    pattern: action('hr-core/employees', 'emergency-contacts'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeeEmergencyContacts),
    queryKeys: noQuery,
    responseSchema: hrEmployeeEmergencyContactSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmergencyContactDetail,
    method: 'PATCH',
    pattern: detail('hr-core/emergency-contacts'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.emergencyContact),
    queryKeys: noQuery,
    responseSchema: hrEmployeeEmergencyContactSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeBankAccount,
    method: 'PATCH',
    pattern: action('hr-core/employees', 'bank-account'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeeBankAccount),
    queryKeys: noQuery,
    responseSchema: hrEmployeeBankAccountSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeAssignments,
    method: 'POST',
    pattern: action('hr-core/employees', 'assignments'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeeAssignments),
    queryKeys: noQuery,
    responseSchema: hrEmployeeAssignmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrAssignmentEnd,
    method: 'PATCH',
    pattern: action('hr-core/assignments', 'end'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.assignmentEnd),
    queryKeys: noQuery,
    responseSchema: hrEmployeeAssignmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDeadlines,
    method: 'GET',
    pattern: exact('/hr-core/deadlines'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.deadlines),
    queryKeys: noQuery,
    responseSchema: hrDeadlineCenterSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeDocuments,
    method: 'POST',
    pattern: action('hr-core/employees', 'documents'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeeDocuments),
    queryKeys: noQuery,
    responseSchema: hrEmployeeDocumentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDocumentDetail,
    method: 'PATCH',
    pattern: detail('hr-core/hr-documents'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.document),
    queryKeys: noQuery,
    responseSchema: hrEmployeeDocumentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDocumentVersions,
    method: 'POST',
    pattern: action('hr-core/hr-documents', 'versions'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.documentVersions),
    queryKeys: noQuery,
    responseSchema: hrEmployeeDocumentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrDocumentVersionContent,
    method: 'GET',
    pattern: action('hr-core/hr-document-versions', 'content'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.documentVersionContent),
    queryKeys: noQuery,
    responseSchema: hrDocumentContentSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrLifecycleJourneys,
    method: 'GET',
    pattern: exact('/hr-core/lifecycle-journeys'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.lifecycleJourneys),
    queryKeys: noQuery,
    responseSchema: hrLifecycleJourneyListSchema,
    kind: 'json',
    idempotency: 'forbidden',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrLifecycleJourneys,
    method: 'POST',
    pattern: exact('/hr-core/lifecycle-journeys'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.lifecycleJourneys),
    queryKeys: noQuery,
    responseSchema: hrLifecycleJourneySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrHiring,
    method: 'POST',
    pattern: exact('/hr-core/hiring'),
    build: staticBuilder(erpMarocUpstreamRoutes.hrCore.hiring),
    queryKeys: noQuery,
    responseSchema: hrLifecycleJourneySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrLifecycleTaskDetail,
    method: 'PATCH',
    pattern: detail('hr-core/lifecycle-tasks'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.lifecycleTask),
    queryKeys: noQuery,
    responseSchema: hrLifecycleTaskSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrLifecycleJourneyStatus,
    method: 'PATCH',
    pattern: action('hr-core/lifecycle-journeys', 'status'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.lifecycleJourneyStatus),
    queryKeys: noQuery,
    responseSchema: hrLifecycleJourneySchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrEmployeeContracts,
    method: 'POST',
    pattern: action('hr-core/employees', 'contracts'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.employeeContracts),
    queryKeys: noQuery,
    responseSchema: hrEmploymentContractSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrContractStatus,
    method: 'PATCH',
    pattern: action('hr-core/contracts', 'status'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.contractStatus),
    queryKeys: noQuery,
    responseSchema: hrEmploymentContractSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrContractAmendments,
    method: 'POST',
    pattern: action('hr-core/contracts', 'amendments'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.contractAmendments),
    queryKeys: noQuery,
    responseSchema: hrContractAmendmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
  defineRoute({
    routeId: erpMarocRouteIds.hrAmendmentStatus,
    method: 'PATCH',
    pattern: action('hr-core/amendments', 'status'),
    build: idBuilder(erpMarocUpstreamRoutes.hrCore.amendmentStatus),
    queryKeys: noQuery,
    responseSchema: hrContractAmendmentSchema,
    kind: 'json',
    idempotency: 'required',
  }),
];

export const ERP_MAROC_ROUTE_POLICY: readonly ErpMarocRoute[] =
  Object.freeze(routes);

const rejectRoute = (): never => {
  throw new Error('ERP route is not allowed');
};

const assertSafePath = (path: string): void => {
  if (
    typeof path !== 'string' ||
    !path.startsWith('/') ||
    path.startsWith('//') ||
    path.includes('?') ||
    path.includes('#') ||
    path.includes('%') ||
    path.includes('\\') ||
    /[\u0000-\u0020\u007f]/.test(path) ||
    /(^|\/)\.{1,2}(\/|$)/.test(path)
  ) {
    rejectRoute();
  }
};

const readQueryEntries = (query: ErpMarocQuery): [string, string][] => {
  if (query instanceof URLSearchParams) {
    const entries = [...query.entries()];
    if (new Set(entries.map(([key]) => key)).size !== entries.length) {
      rejectRoute();
    }
    return entries;
  }
  if (query === null || typeof query !== 'object' || Array.isArray(query)) {
    rejectRoute();
  }

  return Object.entries(query).map(([key, value]) => {
    if (typeof value !== 'string') return rejectRoute();
    return [key, value];
  });
};

const civilDate = /^\d{4}-\d{2}-\d{2}$/;
const paymentStatuses = new Set([
  'PENDING_ALLOCATION',
  'POSTED',
  'REVERSED',
  'CANCELLED',
]);
const paymentKinds = new Set(['RECEIPT', 'REVERSAL']);
const paymentMethods = new Set([
  'CASH',
  'BANK_TRANSFER',
  'CHECK',
  'CARD',
  'DIRECT_DEBIT',
  'OTHER',
]);
const chequeDirections = new Set(['RECEIVED', 'ISSUED']);
const chequeInstrumentTypes = new Set(['CHEQUE', 'LCN']);
const chequeStatuses = new Set([
  'DRAFT',
  'PRINTED',
  'SIGNED',
  'DELIVERED',
  'IN_PORTFOLIO',
  'DEPOSITED',
  'CLEARED',
  'REJECTED',
  'STOPPED',
  'CANCELLED',
]);
const creditNoteStatuses = new Set(['DRAFT', 'VALIDATED', 'CANCELLED']);
const reminderStatuses = new Set([
  'PROPOSED',
  'APPROVED',
  'PROCESSING',
  'SENT',
  'CANCELLED',
  'SUPERSEDED',
  'FAILED',
  'RECONCILIATION_REQUIRED',
]);
const reminderLevels = new Set(['LEVEL_1', 'LEVEL_2', 'LEVEL_3']);
const accountingEntryStatuses = new Set([
  'DRAFT',
  'VALIDATED',
  'LOCKED',
  'REJECTED',
]);
const accountingSourceTypes = new Set([
  'MANUAL',
  'REVERSAL',
  'INVOICE',
  'PAYMENT',
  'CREDIT_NOTE',
  'SUPPLIER_INVOICE',
  'SUPPLIER_PAYMENT',
  'PAYROLL',
  'EXPENSE_NOTE',
  'PROVISION',
  'CLOSING',
  'OPENING_BALANCE',
]);
const accountingProvisionStatuses = new Set([
  'DRAFT',
  'ACTIVE',
  'REVERSED',
  'CANCELLED',
]);
const documentTypes = new Set([
  'SUPPLIER_INVOICE',
  'CUSTOMER_INVOICE',
  'BANK_STATEMENT',
  'RECEIPT',
  'CONTRACT',
  'FISCAL',
  'PAYROLL',
  'OTHER',
]);

const isValidCivilDate = (value: string): boolean => {
  if (!civilDate.test(value)) return false;
  const [year, month, day] = value.split('-').map(Number);
  return (
    new Date(Date.UTC(year, month - 1, day)).toISOString().slice(0, 10) ===
    value
  );
};

const assertNormalizedQueryValue = (
  routeId: ErpMarocRouteId,
  key: string,
  value: string,
): void => {
  if (value.length === 0 || value.trim() !== value) rejectRoute();
  if (
    key === 'cursor' ||
    key === 'tierId' ||
    key === 'invoiceId' ||
    key === 'bankAccountId' ||
    key === 'exerciceId'
  ) {
    if (!uuidSchema.safeParse(value).success) rejectRoute();
    return;
  }
  if (key === 'limit') {
    if (!/^(?:[1-9]|[1-9]\d|100)$/.test(value)) rejectRoute();
    return;
  }
  if (key === 'from' || key === 'to' || key === 'dueBefore') {
    if (!isValidCivilDate(value)) rejectRoute();
    return;
  }
  if (
    routeId === erpMarocRouteIds.accountingGrandLivre ||
    routeId === erpMarocRouteIds.accountingBalance ||
    routeId === erpMarocRouteIds.accountingLettrageSuggestions
  ) {
    if (key === 'includeDraft' && value === 'true') return;
    if (
      routeId === erpMarocRouteIds.accountingGrandLivre &&
      key === 'accountCode' &&
      /^[A-Za-z0-9][A-Za-z0-9.-]{0,31}$/.test(value)
    ) {
      return;
    }
    if (
      routeId === erpMarocRouteIds.accountingLettrageSuggestions &&
      key === 'accountCode' &&
      /^[A-Za-z0-9][A-Za-z0-9.-]{0,31}$/.test(value)
    ) {
      return;
    }
  }
  if (routeId === erpMarocRouteIds.paymentsCollection) {
    if (key === 'status' && paymentStatuses.has(value)) return;
    if (key === 'kind' && paymentKinds.has(value)) return;
    if (key === 'method' && paymentMethods.has(value)) return;
  }
  if (routeId === erpMarocRouteIds.chequesCollection) {
    if (key === 'direction' && chequeDirections.has(value)) return;
    if (key === 'instrumentType' && chequeInstrumentTypes.has(value)) return;
    if (key === 'status' && chequeStatuses.has(value)) return;
    if (
      key === 'search' &&
      value.length <= 120 &&
      !/[\u0000-\u001f\u007f-\u009f]/.test(value)
    ) {
      return;
    }
  }
  if (routeId === erpMarocRouteIds.chequeAlerts) {
    if (!/^\d+$/.test(value)) rejectRoute();
    const parsed = Number(value);
    if (key === 'horizonDays' && parsed >= 1 && parsed <= 90) return;
    if (key === 'staleDepositDays' && parsed >= 1 && parsed <= 30) return;
    if (key === 'lowBookThreshold' && parsed >= 1 && parsed <= 100) return;
  }
  if (routeId === erpMarocRouteIds.creditNotesCollection) {
    if (key === 'status' && creditNoteStatuses.has(value)) return;
  }
  if (routeId === erpMarocRouteIds.remindersCollection) {
    if (key === 'status' && reminderStatuses.has(value)) return;
    if (key === 'level' && reminderLevels.has(value)) return;
  }
  if (routeId === erpMarocRouteIds.accountingEntriesCollection) {
    if (key === 'status' && accountingEntryStatuses.has(value)) return;
    if (key === 'sourceType' && accountingSourceTypes.has(value)) return;
  }
  if (routeId === erpMarocRouteIds.accountingProvisionsCollection) {
    if (key === 'status' && accountingProvisionStatuses.has(value)) return;
  }
  if (routeId === erpMarocRouteIds.documentsCollection) {
    if (key === 'type' && documentTypes.has(value)) return;
    if (
      (key === 'search' || key === 'tag') &&
      value.length <= 120 &&
      !/[\u0000-\u001f\u007f-\u009f]/.test(value)
    ) {
      return;
    }
  }
  if (
    routeId === erpMarocRouteIds.liasseExport &&
    key === 'format' &&
    (value === 'xlsx' || value === 'json')
  ) {
    return;
  }
  if (
    routeId === erpMarocRouteIds.fiscalDeclarationAdc080f &&
    key === 'regime' &&
    (value === 'DEBIT' || value === 'ENCAISSEMENT')
  ) {
    return;
  }
  if (
    routeId === erpMarocRouteIds.fiscalDeadlinesSeed &&
    key === 'year' &&
    /^(?:20\d{2}|21\d{2}|2200)$/.test(value)
  ) {
    return;
  }
  rejectRoute();
};

const buildQueryString = (
  route: ErpMarocRoute,
  query: ErpMarocQuery,
): string => {
  const entries = readQueryEntries(query);
  const values = new Map<string, string>();

  for (const [key, value] of entries) {
    if (!route.queryKeys.includes(key) || values.has(key)) rejectRoute();
    assertNormalizedQueryValue(route.routeId, key, value);
    values.set(key, value);
  }
  if (
    (route.routeId === erpMarocRouteIds.accountingGrandLivre ||
      route.routeId === erpMarocRouteIds.accountingLettrageSuggestions) &&
    !values.has('accountCode')
  ) {
    rejectRoute();
  }
  if (
    (route.routeId === erpMarocRouteIds.fiscalTvaProrata ||
      route.routeId === erpMarocRouteIds.fiscalTvaProrataAnnual) &&
    !values.has('exerciceId')
  ) {
    rejectRoute();
  }
  if (
    route.routeId === erpMarocRouteIds.fiscalDeadlinesSeed &&
    !values.has('year')
  ) {
    rejectRoute();
  }
  if (
    values.has('from') &&
    values.has('to') &&
    values.get('from')! > values.get('to')!
  ) {
    rejectRoute();
  }

  const params = new URLSearchParams();
  for (const key of route.queryKeys) {
    const value = values.get(key);
    if (value !== undefined) params.append(key, value);
  }
  const serialized = params.toString();
  return serialized.length === 0 ? '' : `?${serialized}`;
};

export const resolveErpRoute = (
  method: string,
  path: string,
  query: ErpMarocQuery,
): ResolvedErpMarocRoute => {
  assertSafePath(path);
  const route = ERP_MAROC_ROUTE_POLICY.find((candidate) => {
    if (candidate.method !== method) return false;
    return candidate.pattern.test(path);
  });
  const matchedRoute = route ?? rejectRoute();

  const match = path.match(matchedRoute.pattern) ?? rejectRoute();
  let builtPath: string;
  try {
    builtPath = matchedRoute.build(match);
  } catch {
    return rejectRoute();
  }
  const upstreamPath = `${builtPath}${buildQueryString(matchedRoute, query)}`;

  return Object.freeze({
    routeId: matchedRoute.routeId,
    method: matchedRoute.method,
    upstreamPath,
    responseSchema: matchedRoute.responseSchema,
    kind: matchedRoute.kind,
    idempotency: matchedRoute.idempotency,
  });
};
