import {
  attendanceAssignmentListSchema,
  attendanceAssignmentSchema,
  attendancePeriodListSchema,
  attendancePeriodSchema,
  attendancePolicyListSchema,
  attendancePolicySchema,
  attendanceRecordListSchema,
  attendanceRecordSchema,
  employeePortalDashboardSchema,
  employeePortalEmployeeListSchema,
  employeePortalFileSchema,
  employeePortalRequestListSchema,
  employeePortalRequestSchema,
  clientPortalCommentSchema,
  clientPortalRequestListSchema,
  clientPortalRequestSchema,
  talentEmployeeSkillListSchema,
  talentEmployeeSkillSchema,
  talentPerformanceCycleListSchema,
  talentPerformanceCycleSchema,
  talentPerformanceReviewListSchema,
  talentPerformanceReviewSchema,
  talentRecruitmentApplicationListSchema,
  talentRecruitmentApplicationSchema,
  talentRecruitmentInterviewSchema,
  talentRecruitmentJobListSchema,
  talentRecruitmentJobSchema,
  talentSkillListSchema,
  talentSkillSchema,
  talentTrainingCourseListSchema,
  talentTrainingCourseSchema,
  talentTrainingEnrollmentListSchema,
  talentTrainingEnrollmentSchema,
  talentTrainingSessionListSchema,
  talentTrainingSessionSchema,
  erpAccountingEntryPageSchema,
  erpAccountingEntrySchema,
  erpAccountingProvisionListSchema,
  erpAccountingProvisionSchema,
  erpFixedAssetCategoryListSchema,
  erpFixedAssetCategorySchema,
  erpFixedAssetListSchema,
  erpFixedAssetSchema,
  erpAccountingAccountSchema,
  erpAccountingJournalSchema,
  erpAccountingPeriodSchema,
  erpAccountingReviewAccountSchema,
  erpAccountingReviewDossierSchema,
  erpAccountingReviewExportSchema,
  erpAccountingReferencesSchema,
  erpAccountingReviewTaskListSchema,
  erpAccountingReviewTaskSchema,
  erpBalanceReportSchema,
  erpBankAccountListSchema,
  erpBankAccountSchema,
  erpChequeAlertsSchema,
  erpChequeBookListSchema,
  erpChequeBookSchema,
  erpChequeDepositEligibleListSchema,
  erpChequeDepositSlipListSchema,
  erpChequeDepositSlipSchema,
  erpChequePageSchema,
  erpChequeReconciliationCandidatesSchema,
  erpChequeSchema,
  erpChequeSummarySchema,
  erpCreditNotePageSchema,
  erpCreditNoteSchema,
  erpCustomerReturnEligibleLineListSchema,
  erpCustomerReturnListSchema,
  erpCustomerReturnSchema,
  erpContextSchema,
  erpDocumentContentSchema,
  erpDocumentListSchema,
  erpDocumentSchema,
  erpDeliveryNoteListSchema,
  erpDeliveryNoteSchema,
  erpExpenseNoteListSchema,
  erpExpenseNoteSchema,
  erpAnalyticAllocationSchema,
  erpAnalyticAxisListSchema,
  erpAnalyticAxisSchema,
  erpBudgetListSchema,
  erpBudgetSchema,
  erpBudgetVarianceSchema,
  erpRecurringInvoiceListSchema,
  erpRecurringInvoiceRunSchema,
  erpRecurringInvoiceSchema,
  erpExchangeRateListSchema,
  erpExchangeRateSchema,
  erpPortalAccessGrantSchema,
  erpPortalAccessHistorySchema,
  erpPortalAccessListSchema,
  erpPortalAccessRenewSchema,
  erpPortalAccessSchema,
  erpPortalInvitationSchema,
  erpEmployeeListSchema,
  erpPayslipListSchema,
  erpPayslipSchema,
  erpAiAccountingAnswerSchema,
  erpAiAccountingConversationListSchema,
  erpAiAccountingSafeQueryResultSchema,
  erpAiAccountingStatusSchema,
  erpAiAccountingSuggestionBatchSchema,
  erpAiAccountingSuggestionListSchema,
  erpAiAccountingSuggestionSchema,
  erpAiCategorizationRuleListSchema,
  erpAiCategorizationRuleSchema,
  erpEligibleInvoicePageSchema,
  erpInvoicePageSchema,
  erpInvoiceReadSchema,
  erpInvoiceSchema,
  erpGrossMarginReportSchema,
  erpInventoryCountListSchema,
  erpInventoryCountSchema,
  erpInventoryThresholdListSchema,
  erpInventoryThresholdSchema,
  erpLeaveRequestSchema,
  erpOnboardingImportApplyResultSchema,
  erpOnboardingImportPreviewSchema,
  erpOnboardingConfigurationSchema,
  erpOnboardingReadinessSchema,
  erpSocieteLegalSummarySchema,
  erpGrandLivreReportSchema,
  erpExerciseClosingResultSchema,
  erpExerciseListSchema,
  erpExerciseSchema,
  erpFecExportSchema,
  erpFecImportResultSchema,
  erpFinancialStatementsSchema,
  erpFiscalDeadlineListSchema,
  erpFiscalDeadlineSchema,
  erpFileExportSchema,
  erpLiasseDeleteResultSchema,
  erpLiasseExportSchema,
  erpLiasseRowSchema,
  erpLiasseTableDetailSchema,
  erpLiasseTableSummaryListSchema,
  erpLiasseValidationSchema,
  erpRegulatoryFileSchema,
  erpRegulatorySubmissionListSchema,
  erpRegulatorySubmissionSchema,
  erpLettrageMatchSchema,
  erpLettrageSuggestionsSchema,
  erpTaxDeclarationListSchema,
  erpTaxDeclarationSchema,
  erpTaxPaymentCandidateListSchema,
  erpTaxPaymentListSchema,
  erpTaxPaymentSchema,
  erpTvaProrataPeriodListSchema,
  erpTvaProrataPeriodSchema,
  erpAnnualTvaProrataSchema,
  erpTvaProrataPostingSchema,
  hrAccessAdministrationSchema,
  hrAccessContextSchema,
  hrAccessGrantSchema,
  hrContractAmendmentSchema,
  hrCostCenterListSchema,
  hrCostCenterSchema,
  hrCoreSummarySchema,
  hrDepartmentListSchema,
  hrDepartmentSchema,
  hrEmployeeBankAccountSchema,
  hrEmployeeDependantSchema,
  hrEmployeeDetailSchema,
  hrEmployeeEmergencyContactSchema,
  hrEmployeeImportCommitResultSchema,
  hrEmployeeImportPreviewSchema,
  hrEmployeeImportTemplateSchema,
  hrEmployeeListSchema,
  hrEmployeePrivateProfileSchema,
  hrEmployeeAssignmentSchema,
  hrEmployeeDocumentSchema,
  hrDocumentContentSchema,
  hrDeadlineCenterSchema,
  hrEmploymentContractSchema,
  hrEstablishmentListSchema,
  hrEstablishmentSchema,
  hrGradeListSchema,
  hrGradeSchema,
  hrJobPositionListSchema,
  hrJobPositionSchema,
  hrLifecycleJourneyListSchema,
  hrLifecycleJourneySchema,
  hrLifecycleTaskSchema,
  hrTeamListSchema,
  hrTeamSchema,
  hrWorkLocationListSchema,
  hrWorkLocationSchema,
  marketingAutomationListSchema,
  marketingAutomationSchema,
  marketingCampaignListSchema,
  marketingCampaignSchema,
  marketingContactListSchema,
  marketingContactSchema,
  marketingEventListSchema,
  marketingEventSchema,
  marketingOverviewSchema,
  marketingScoringRuleListSchema,
  marketingScoringRuleSchema,
  marketingSegmentListSchema,
  marketingSegmentSchema,
  marketingSegmentSyncResultSchema,
  marketingTierImportResultSchema,
  payrollComponentListSchema,
  payrollControlDefinitionListSchema,
  payrollLegalSourceListSchema,
  payrollRegulatorySeedResultSchema,
  payrollRegulatorySummarySchema,
  payrollRuleListSchema,
  erpPaymentPageSchema,
  erpPaymentSchema,
  erpProductListSchema,
  erpProductSchema,
  erpPurchaseOrderListSchema,
  erpPurchaseOrderSchema,
  erpPurchaseReceiptListSchema,
  erpPurchaseReceiptSchema,
  erpSupplierInvoiceListSchema,
  erpSupplierInvoiceSchema,
  erpSupplierInvoiceDetailSchema,
  erpSupplierPaymentPreparationListSchema,
  erpSupplierPaymentPreparationSchema,
  erpQuoteListSchema,
  erpQuoteSchema,
  erpReminderPageSchema,
  erpReminderScanResultSchema,
  erpReminderSchema,
  erpReplenishmentSuggestionListSchema,
  erpSalesOrderListSchema,
  erpSalesOrderSchema,
  erpStockLevelListSchema,
  erpStockMovementListSchema,
  erpStockMovementSchema,
  erpTierListSchema,
  erpTierSchema,
  erpWarehouseListSchema,
  erpWarehouseSchema,
} from 'twenty-shared/erp-maroc';

import {
  ERP_MAROC_ROUTE_POLICY,
  resolveErpRoute,
} from './erp-maroc-route-policy';

const id = '11111111-1111-4111-8111-111111111111';
const otherId = '22222222-2222-4222-8222-222222222222';
const uuidV7 = '0193f6ea-7c39-7aa2-8000-000000000000';

const requiredIdempotencyRoutes = new Set([
  'POST /onboarding/accounting-bootstrap',
  'POST /onboarding/imports/preview',
  'POST /onboarding/imports/apply',
  'POST /bank-accounts',
  'POST /warehouses',
  'POST /inventory/adjustments',
  'POST /inventory/transfers',
  'POST /inventory/counts',
  `POST /inventory/counts/${id}/validate`,
  `POST /inventory/counts/${id}/cancel`,
  'POST /inventory/thresholds',
  'POST /customer-returns',
  `POST /customer-returns/${id}/validate`,
  `POST /customer-returns/${id}/cancel`,
  'POST /accounting/entries',
  `PATCH /accounting/entries/${id}`,
  `POST /accounting/entries/${id}/duplicate`,
  'POST /accounting/provisions',
  `PATCH /accounting/provisions/${id}`,
  `POST /accounting/provisions/${id}/post`,
  `POST /accounting/provisions/${id}/reverse`,
  `POST /accounting/provisions/${id}/cancel`,
  'POST /accounting/fixed-assets/categories',
  `PATCH /accounting/fixed-assets/categories/${id}`,
  'POST /accounting/fixed-assets',
  `PATCH /accounting/fixed-assets/${id}`,
  `POST /accounting/fixed-assets/${id}/activate`,
  `POST /accounting/fixed-assets/depreciations/${id}/post`,
  `POST /accounting/fixed-assets/${id}/dispose`,
  'POST /payments',
  `POST /payments/${id}/allocate`,
  `POST /payments/${id}/terminate`,
  'POST /cheques',
  'POST /cheques/books',
  'POST /cheques/deposit-slips',
  `POST /cheques/${id}/transition`,
  `POST /cheques/${id}/reconcile`,
  `POST /cheques/${id}/unreconcile`,
  'POST /credit-notes',
  `PATCH /credit-notes/${id}`,
  `POST /credit-notes/${id}/validate`,
  `POST /credit-notes/${id}/allocate`,
  `POST /credit-notes/${id}/cancel`,
  'POST /reminders/scan',
  `POST /reminders/${id}/approve`,
  `POST /reminders/${id}/cancel`,
  `POST /accounting/entries/${id}/validate`,
  `POST /accounting/entries/${id}/reject`,
  `POST /accounting/entries/${id}/reverse`,
  'POST /documents',
  `POST /documents/${id}/ocr/retry`,
  `POST /documents/${id}/ocr/validate`,
  `POST /documents/${id}/create-supplier-invoice`,
  'POST /operations/expense-notes',
  `POST /operations/expense-notes/${id}/submit`,
  `PATCH /operations/expense-notes/${id}/decision`,
  `POST /operations/expense-notes/${id}/pay`,
  'POST /operations/analytics',
  'POST /operations/analytics/allocations',
  'POST /operations/budgets',
  `POST /operations/budgets/${id}/approve`,
  'POST /operations/recurring-invoices',
  `PATCH /operations/recurring-invoices/${id}/status`,
  'POST /operations/recurring-invoices/run',
  'POST /operations/exchange-rates',
  'POST /operations/portal-access',
  `POST /operations/portal-access/${id}/revoke`,
  `POST /operations/portal-access/${id}/resend`,
  `POST /operations/portal-access/${id}/renew`,
  `POST /portal-admin/requests/${id}/comments`,
  `PATCH /portal-admin/requests/${id}`,
  'POST /fiscal/tva/calculate',
  'POST /fiscal/tva/prorata/calculate',
  'POST /fiscal/tva/prorata/annual/post',
  'POST /fiscal/is/calculate',
  `PATCH /fiscal/declarations/${id}/status`,
  `POST /fiscal/declarations/${id}/payments`,
  'POST /fiscal/deadlines/seed',
  `PATCH /fiscal/deadlines/${id}/complete`,
  'POST /accounting/references/accounts',
  `PATCH /accounting/references/accounts/${id}`,
  'POST /accounting/references/journals',
  `PATCH /accounting/references/journals/${id}`,
  'POST /accounting/lettrage/match',
  'POST /accounting/lettrage/unmatch',
  'POST /accounting-compliance/exercises',
  `POST /accounting-compliance/exercises/${id}/review`,
  `POST /accounting-compliance/exercises/${id}/review-refresh`,
  `PATCH /accounting-compliance/review-tasks/${id}`,
  `POST /accounting-compliance/review-tasks/${id}/decision`,
  `PATCH /accounting-compliance/review-accounts/${id}`,
  `POST /accounting-compliance/periods/${id}/close`,
  `POST /accounting-compliance/periods/${id}/reopen`,
  `POST /accounting-compliance/exercises/${id}/close`,
  'POST /accounting-compliance/fec/import',
  `PATCH /liasse/submissions/${id}/external-validation`,
  'POST /ai-accounting/rules',
  `PATCH /ai-accounting/rules/${id}`,
  `POST /ai-accounting/rules/${id}/deactivate`,
  'POST /ai-accounting/categorize',
  'POST /ai-accounting/reconcile',
  `PATCH /ai-accounting/suggestions/${id}`,
  'POST /ai-accounting/safe-query',
  'POST /ai-accounting/ask',
  `PUT /liasse/exercises/${id}/tables/T12/rows/ASSOCIE_1`,
  `DELETE /liasse/exercises/${id}/tables/T12/rows/ASSOCIE_1`,
  `POST /supplier-invoices/${id}/payment-preparations`,
  `POST /supplier-payment-preparations/${id}/cancel`,
  'POST /marketing/contacts/import-tiers',
  `POST /marketing/contacts/${id}/consent`,
  'POST /marketing/segments',
  `POST /marketing/segments/${id}/sync`,
  'POST /marketing/campaigns',
  `POST /marketing/campaigns/${id}/send`,
  `POST /marketing/campaigns/${id}/refresh`,
  'POST /marketing/automations',
  `POST /marketing/automations/${id}/activate`,
  `POST /marketing/automations/${id}/pause`,
  'POST /marketing/scoring-rules',
  `POST /marketing/scoring-rules/${id}/toggle`,
  'POST /marketing/events',
  'POST /payroll/regulatory/seed/morocco-2026',
  'POST /payroll/payslips/generate',
  `POST /payroll/payslips/${id}/validate`,
  `POST /payroll/payslips/${id}/pay`,
  'POST /attendance/policies',
  `PATCH /attendance/policies/${id}`,
  'POST /attendance/assignments',
  'POST /attendance/records',
  `POST /attendance/records/${id}/submit`,
  `POST /attendance/records/${id}/decision`,
  'POST /attendance/periods/recompute',
  `POST /attendance/periods/${id}/approve`,
  'POST /talent/recruitment/jobs',
  `PATCH /talent/recruitment/jobs/${id}/status`,
  'POST /talent/recruitment/applications',
  `PATCH /talent/recruitment/applications/${id}/status`,
  `POST /talent/recruitment/applications/${id}/interviews`,
  `PATCH /talent/recruitment/interviews/${id}`,
  `POST /talent/recruitment/applications/${id}/hire`,
  'POST /talent/training/courses',
  'POST /talent/training/sessions',
  `PATCH /talent/training/sessions/${id}/status`,
  'POST /talent/training/enrollments',
  `PATCH /talent/training/enrollments/${id}`,
  'POST /talent/skills',
  'POST /talent/employee-skills',
  'POST /talent/performance/cycles',
  `PATCH /talent/performance/cycles/${id}/status`,
  'POST /talent/performance/reviews',
  `PATCH /talent/performance/reviews/${id}`,
  'POST /employee-portal/leaves',
  `POST /employee-portal/leaves/${id}/cancel`,
  'POST /employee-portal/requests',
  `POST /employee-portal/requests/${id}/cancel`,
  `PATCH /employee-portal/admin/requests/${id}`,
  'POST /hr-core/access/grants',
  'POST /hr-core/establishments',
  `PATCH /hr-core/establishments/${id}`,
  'POST /hr-core/grades',
  `PATCH /hr-core/grades/${id}`,
  'POST /hr-core/cost-centers',
  `PATCH /hr-core/cost-centers/${id}`,
  'POST /hr-core/teams',
  `PATCH /hr-core/teams/${id}`,
  'POST /hr-core/work-locations',
  `PATCH /hr-core/work-locations/${id}`,
  'POST /hr-core/departments',
  `PATCH /hr-core/departments/${id}`,
  'POST /hr-core/job-positions',
  `PATCH /hr-core/job-positions/${id}`,
  'POST /hr-core/employee-import/preview',
  'POST /hr-core/employee-import/commit',
  `PATCH /hr-core/employees/${id}/personal-details`,
  `POST /hr-core/employees/${id}/dependants`,
  `PATCH /hr-core/dependants/${id}`,
  `POST /hr-core/employees/${id}/emergency-contacts`,
  `PATCH /hr-core/emergency-contacts/${id}`,
  `PATCH /hr-core/employees/${id}/bank-account`,
  `POST /hr-core/employees/${id}/assignments`,
  `PATCH /hr-core/assignments/${id}/end`,
  `POST /hr-core/employees/${id}/documents`,
  `PATCH /hr-core/hr-documents/${id}`,
  `POST /hr-core/hr-documents/${id}/versions`,
  'POST /hr-core/lifecycle-journeys',
  'POST /hr-core/hiring',
  `PATCH /hr-core/lifecycle-tasks/${id}`,
  `PATCH /hr-core/lifecycle-journeys/${id}/status`,
  `POST /hr-core/employees/${id}/contracts`,
  `PATCH /hr-core/contracts/${id}/status`,
  `POST /hr-core/contracts/${id}/amendments`,
  `PATCH /hr-core/amendments/${id}/status`,
]);

const approvedRoutes = [
  ['GET', '/context', 'context', erpContextSchema],
  [
    'POST',
    '/onboarding/accounting-bootstrap',
    'onboarding.accounting-bootstrap',
    erpOnboardingReadinessSchema,
  ],
  [
    'POST',
    '/onboarding/complete',
    'onboarding.complete',
    erpOnboardingReadinessSchema,
  ],
  [
    'GET',
    '/onboarding/configuration',
    'onboarding.configuration',
    erpOnboardingConfigurationSchema,
  ],
  [
    'PATCH',
    '/onboarding/legal-profile',
    'onboarding.legal-profile',
    erpSocieteLegalSummarySchema,
  ],
  [
    'GET',
    '/onboarding/readiness',
    'onboarding.readiness',
    erpOnboardingReadinessSchema,
  ],
  [
    'POST',
    '/onboarding/imports/preview',
    'onboarding.import.preview',
    erpOnboardingImportPreviewSchema,
  ],
  [
    'POST',
    '/onboarding/imports/apply',
    'onboarding.import.apply',
    erpOnboardingImportApplyResultSchema,
  ],
  [
    'GET',
    '/bank-accounts',
    'bank-accounts.collection',
    erpBankAccountListSchema,
  ],
  ['POST', '/bank-accounts', 'bank-accounts.collection', erpBankAccountSchema],
  ['GET', '/warehouses', 'warehouses.collection', erpWarehouseListSchema],
  ['POST', '/warehouses', 'warehouses.collection', erpWarehouseSchema],
  ['GET', '/inventory/levels', 'inventory.levels', erpStockLevelListSchema],
  [
    'GET',
    '/inventory/movements',
    'inventory.movements',
    erpStockMovementListSchema,
  ],
  [
    'GET',
    '/inventory/gross-margins',
    'inventory.grossMargins',
    erpGrossMarginReportSchema,
  ],
  [
    'POST',
    '/inventory/adjustments',
    'inventory.adjustments',
    erpStockMovementSchema,
  ],
  [
    'POST',
    '/inventory/transfers',
    'inventory.transfers',
    erpStockMovementListSchema,
  ],
  ['GET', '/inventory/counts', 'inventory.counts', erpInventoryCountListSchema],
  ['POST', '/inventory/counts', 'inventory.counts', erpInventoryCountSchema],
  [
    'POST',
    `/inventory/counts/${id}/validate`,
    'inventory.count.validate',
    erpInventoryCountSchema,
  ],
  [
    'POST',
    `/inventory/counts/${id}/cancel`,
    'inventory.count.cancel',
    erpInventoryCountSchema,
  ],
  [
    'GET',
    '/inventory/thresholds',
    'inventory.thresholds',
    erpInventoryThresholdListSchema,
  ],
  [
    'POST',
    '/inventory/thresholds',
    'inventory.thresholds',
    erpInventoryThresholdSchema,
  ],
  [
    'GET',
    '/inventory/replenishment-suggestions',
    'inventory.replenishmentSuggestions',
    erpReplenishmentSuggestionListSchema,
  ],
  ['GET', '/sales-orders', 'sales-orders.collection', erpSalesOrderListSchema],
  [
    'POST',
    `/sales-orders/from-quote/${id}`,
    'sales-orders.fromQuote',
    erpSalesOrderSchema,
  ],
  ['GET', `/sales-orders/${id}`, 'sales-orders.detail', erpSalesOrderSchema],
  [
    'POST',
    `/sales-orders/${id}/confirm`,
    'sales-orders.confirm',
    erpSalesOrderSchema,
  ],
  [
    'POST',
    `/sales-orders/${id}/reservations`,
    'sales-orders.reserve',
    erpSalesOrderSchema,
  ],
  [
    'POST',
    `/sales-orders/${id}/preparation`,
    'sales-orders.prepare',
    erpSalesOrderSchema,
  ],
  [
    'POST',
    `/sales-orders/${id}/cancel`,
    'sales-orders.cancel',
    erpSalesOrderSchema,
  ],
  [
    'GET',
    `/sales-orders/${id}/deliveries`,
    'sales-orders.deliveries',
    erpDeliveryNoteListSchema,
  ],
  [
    'POST',
    `/sales-orders/${id}/deliveries`,
    'sales-orders.deliveries',
    erpDeliveryNoteSchema,
  ],
  [
    'POST',
    `/sales-orders/${id}/deliveries/${otherId}/cancel`,
    'sales-orders.delivery.cancel',
    erpDeliveryNoteSchema,
  ],
  [
    'POST',
    `/invoices/from-sales-order/${id}`,
    'invoices.fromSalesOrder',
    erpInvoiceSchema,
  ],
  [
    'GET',
    '/customer-returns',
    'customer-returns.collection',
    erpCustomerReturnListSchema,
  ],
  [
    'POST',
    '/customer-returns',
    'customer-returns.collection',
    erpCustomerReturnSchema,
  ],
  [
    'GET',
    '/customer-returns/eligible-lines',
    'customer-returns.eligibleLines',
    erpCustomerReturnEligibleLineListSchema,
  ],
  [
    'GET',
    `/customer-returns/${id}`,
    'customer-returns.detail',
    erpCustomerReturnSchema,
  ],
  [
    'POST',
    `/customer-returns/${id}/validate`,
    'customer-returns.validate',
    erpCustomerReturnSchema,
  ],
  [
    'POST',
    `/customer-returns/${id}/cancel`,
    'customer-returns.cancel',
    erpCustomerReturnSchema,
  ],
  ['GET', '/products', 'products.collection', erpProductListSchema],
  ['POST', '/products', 'products.collection', erpProductSchema],
  ['GET', `/products/${id}`, 'products.detail', erpProductSchema],
  ['PATCH', `/products/${id}`, 'products.detail', erpProductSchema],
  ['DELETE', `/products/${id}`, 'products.detail', erpProductSchema],
  ['GET', '/tiers', 'tiers.collection', erpTierListSchema],
  ['POST', '/tiers', 'tiers.collection', erpTierSchema],
  [
    'POST',
    '/tiers/sync-from-twenty-company',
    'tiers.syncFromTwentyCompany',
    erpTierSchema,
  ],
  ['GET', `/tiers/${id}`, 'tiers.detail', erpTierSchema],
  ['PATCH', `/tiers/${id}`, 'tiers.detail', erpTierSchema],
  ['GET', '/quotes', 'quotes.collection', erpQuoteListSchema],
  ['POST', '/quotes', 'quotes.collection', erpQuoteSchema],
  [
    'POST',
    '/quotes/from-opportunity',
    'quotes.fromOpportunity',
    erpQuoteSchema,
  ],
  ['GET', `/quotes/${id}`, 'quotes.detail', erpQuoteSchema],
  ['PATCH', `/quotes/${id}`, 'quotes.detail', erpQuoteSchema],
  ['POST', `/quotes/${id}/send`, 'quotes.send', erpQuoteSchema],
  ['POST', `/quotes/${id}/accept`, 'quotes.accept', erpQuoteSchema],
  ['POST', `/quotes/${id}/reject`, 'quotes.reject', erpQuoteSchema],
  [
    'GET',
    '/purchase-orders',
    'purchase-orders.collection',
    erpPurchaseOrderListSchema,
  ],
  [
    'POST',
    '/purchase-orders',
    'purchase-orders.collection',
    erpPurchaseOrderSchema,
  ],
  [
    'GET',
    `/purchase-orders/${id}`,
    'purchase-orders.detail',
    erpPurchaseOrderSchema,
  ],
  [
    'POST',
    `/purchase-orders/${id}/confirm`,
    'purchase-orders.confirm',
    erpPurchaseOrderSchema,
  ],
  [
    'POST',
    `/purchase-orders/${id}/cancel`,
    'purchase-orders.cancel',
    erpPurchaseOrderSchema,
  ],
  [
    'GET',
    `/purchase-orders/${id}/receipts`,
    'purchase-orders.receipts',
    erpPurchaseReceiptListSchema,
  ],
  [
    'POST',
    `/purchase-orders/${id}/receipts`,
    'purchase-orders.receipts',
    erpPurchaseReceiptSchema,
  ],
  [
    'GET',
    `/purchase-orders/${id}/supplier-invoices`,
    'purchase-orders.supplierInvoices',
    erpSupplierInvoiceListSchema,
  ],
  [
    'POST',
    `/purchase-orders/${id}/supplier-invoices`,
    'purchase-orders.supplierInvoices',
    erpSupplierInvoiceSchema,
  ],
  [
    'GET',
    `/supplier-invoices/${id}`,
    'supplier-invoices.detail',
    erpSupplierInvoiceDetailSchema,
  ],
  [
    'PATCH',
    `/supplier-invoices/${id}`,
    'supplier-invoices.detail',
    erpSupplierInvoiceDetailSchema,
  ],
  [
    'POST',
    `/supplier-invoices/${id}/approve`,
    'supplier-invoices.approve',
    erpSupplierInvoiceDetailSchema,
  ],
  [
    'POST',
    `/supplier-invoices/${id}/cancel`,
    'supplier-invoices.cancel',
    erpSupplierInvoiceDetailSchema,
  ],
  [
    'GET',
    `/supplier-invoices/${id}/payment-preparations`,
    'supplier-invoices.paymentPreparations',
    erpSupplierPaymentPreparationListSchema,
  ],
  [
    'POST',
    `/supplier-invoices/${id}/payment-preparations`,
    'supplier-invoices.paymentPreparations',
    erpSupplierPaymentPreparationSchema,
  ],
  [
    'POST',
    `/supplier-payment-preparations/${id}/cancel`,
    'supplier-payment-preparations.cancel',
    erpSupplierPaymentPreparationSchema,
  ],
  ['GET', '/invoices', 'invoices.collection', erpInvoicePageSchema],
  ['POST', '/invoices', 'invoices.collection', erpInvoiceSchema],
  [
    'POST',
    `/invoices/from-quote/${id}`,
    'invoices.fromQuote',
    erpInvoiceSchema,
  ],
  ['GET', `/invoices/${id}`, 'invoices.detail', erpInvoiceReadSchema],
  ['PATCH', `/invoices/${id}`, 'invoices.detail', erpInvoiceSchema],
  ['POST', `/invoices/${id}/validate`, 'invoices.validate', erpInvoiceSchema],
  ['POST', `/invoices/${id}/send`, 'invoices.send', erpInvoiceSchema],
  ['GET', `/invoices/${id}/pdf`, 'invoices.pdf', undefined],
  ['GET', '/payments', 'payments.collection', erpPaymentPageSchema],
  ['POST', '/payments', 'payments.collection', erpPaymentSchema],
  ['GET', `/payments/${id}`, 'payments.detail', erpPaymentSchema],
  [
    'GET',
    `/payments/${id}/eligible-invoices`,
    'payments.eligibleInvoices',
    erpEligibleInvoicePageSchema,
  ],
  ['POST', `/payments/${id}/allocate`, 'payments.allocate', erpPaymentSchema],
  ['POST', `/payments/${id}/terminate`, 'payments.terminate', erpPaymentSchema],
  ['GET', '/cheques', 'cheques.collection', erpChequePageSchema],
  ['POST', '/cheques', 'cheques.collection', erpChequeSchema],
  ['GET', '/cheques/books', 'cheques.books', erpChequeBookListSchema],
  ['POST', '/cheques/books', 'cheques.books', erpChequeBookSchema],
  ['GET', '/cheques/summary', 'cheques.summary', erpChequeSummarySchema],
  ['GET', '/cheques/alerts', 'cheques.alerts', erpChequeAlertsSchema],
  [
    'GET',
    '/cheques/deposit-slips/eligible',
    'cheques.depositSlips.eligible',
    erpChequeDepositEligibleListSchema,
  ],
  [
    'GET',
    '/cheques/deposit-slips',
    'cheques.depositSlips',
    erpChequeDepositSlipListSchema,
  ],
  [
    'POST',
    '/cheques/deposit-slips',
    'cheques.depositSlips',
    erpChequeDepositSlipSchema,
  ],
  [
    'GET',
    `/cheques/deposit-slips/${id}`,
    'cheques.depositSlips.detail',
    erpChequeDepositSlipSchema,
  ],
  [
    'GET',
    `/cheques/deposit-slips/${id}/pdf`,
    'cheques.depositSlips.pdf',
    undefined,
  ],
  ['GET', `/cheques/${id}`, 'cheques.detail', erpChequeSchema],
  [
    'GET',
    `/cheques/${id}/reconciliation-candidates`,
    'cheques.reconciliationCandidates',
    erpChequeReconciliationCandidatesSchema,
  ],
  ['POST', `/cheques/${id}/transition`, 'cheques.transition', erpChequeSchema],
  ['POST', `/cheques/${id}/reconcile`, 'cheques.reconcile', erpChequeSchema],
  [
    'POST',
    `/cheques/${id}/unreconcile`,
    'cheques.unreconcile',
    erpChequeSchema,
  ],
  ['GET', '/credit-notes', 'credit-notes.collection', erpCreditNotePageSchema],
  ['POST', '/credit-notes', 'credit-notes.collection', erpCreditNoteSchema],
  ['GET', `/credit-notes/${id}`, 'credit-notes.detail', erpCreditNoteSchema],
  ['PATCH', `/credit-notes/${id}`, 'credit-notes.detail', erpCreditNoteSchema],
  [
    'POST',
    `/credit-notes/${id}/validate`,
    'credit-notes.validate',
    erpCreditNoteSchema,
  ],
  [
    'GET',
    `/credit-notes/${id}/eligible-invoices`,
    'credit-notes.eligibleInvoices',
    erpEligibleInvoicePageSchema,
  ],
  [
    'POST',
    `/credit-notes/${id}/allocate`,
    'credit-notes.allocate',
    erpCreditNoteSchema,
  ],
  [
    'POST',
    `/credit-notes/${id}/cancel`,
    'credit-notes.cancel',
    erpCreditNoteSchema,
  ],
  ['GET', '/reminders', 'reminders.collection', erpReminderPageSchema],
  ['POST', '/reminders/scan', 'reminders.scan', erpReminderScanResultSchema],
  ['GET', `/reminders/${id}`, 'reminders.detail', erpReminderSchema],
  ['POST', `/reminders/${id}/approve`, 'reminders.approve', erpReminderSchema],
  ['POST', `/reminders/${id}/cancel`, 'reminders.cancel', erpReminderSchema],
  [
    'GET',
    '/accounting/entries',
    'accounting.entries.collection',
    erpAccountingEntryPageSchema,
  ],
  [
    'POST',
    '/accounting/entries',
    'accounting.entries.collection',
    erpAccountingEntrySchema,
  ],
  [
    'GET',
    `/accounting/entries/${id}`,
    'accounting.entries.detail',
    erpAccountingEntrySchema,
  ],
  [
    'PATCH',
    `/accounting/entries/${id}`,
    'accounting.entries.detail',
    erpAccountingEntrySchema,
  ],
  [
    'POST',
    `/accounting/entries/${id}/duplicate`,
    'accounting.entries.duplicate',
    erpAccountingEntrySchema,
  ],
  [
    'POST',
    `/accounting/entries/${id}/validate`,
    'accounting.entries.validate',
    erpAccountingEntrySchema,
  ],
  [
    'POST',
    `/accounting/entries/${id}/reject`,
    'accounting.entries.reject',
    erpAccountingEntrySchema,
  ],
  [
    'POST',
    `/accounting/entries/${id}/reverse`,
    'accounting.entries.reverse',
    erpAccountingEntrySchema,
  ],
  [
    'GET',
    '/accounting/provisions',
    'accounting.provisions.collection',
    erpAccountingProvisionListSchema,
  ],
  [
    'POST',
    '/accounting/provisions',
    'accounting.provisions.collection',
    erpAccountingProvisionSchema,
  ],
  [
    'GET',
    `/accounting/provisions/${id}`,
    'accounting.provisions.detail',
    erpAccountingProvisionSchema,
  ],
  [
    'PATCH',
    `/accounting/provisions/${id}`,
    'accounting.provisions.detail',
    erpAccountingProvisionSchema,
  ],
  [
    'POST',
    `/accounting/provisions/${id}/post`,
    'accounting.provisions.post',
    erpAccountingProvisionSchema,
  ],
  [
    'POST',
    `/accounting/provisions/${id}/reverse`,
    'accounting.provisions.reverse',
    erpAccountingProvisionSchema,
  ],
  [
    'POST',
    `/accounting/provisions/${id}/cancel`,
    'accounting.provisions.cancel',
    erpAccountingProvisionSchema,
  ],
  [
    'GET',
    '/accounting/fixed-assets/categories',
    'accounting.fixedAssets.categories',
    erpFixedAssetCategoryListSchema,
  ],
  [
    'POST',
    '/accounting/fixed-assets/categories',
    'accounting.fixedAssets.categories',
    erpFixedAssetCategorySchema,
  ],
  [
    'PATCH',
    `/accounting/fixed-assets/categories/${id}`,
    'accounting.fixedAssets.categoryDetail',
    erpFixedAssetCategorySchema,
  ],
  [
    'GET',
    '/accounting/fixed-assets',
    'accounting.fixedAssets.collection',
    erpFixedAssetListSchema,
  ],
  [
    'POST',
    '/accounting/fixed-assets',
    'accounting.fixedAssets.collection',
    erpFixedAssetSchema,
  ],
  [
    'GET',
    `/accounting/fixed-assets/${id}`,
    'accounting.fixedAssets.detail',
    erpFixedAssetSchema,
  ],
  [
    'PATCH',
    `/accounting/fixed-assets/${id}`,
    'accounting.fixedAssets.detail',
    erpFixedAssetSchema,
  ],
  [
    'POST',
    `/accounting/fixed-assets/${id}/activate`,
    'accounting.fixedAssets.activate',
    erpFixedAssetSchema,
  ],
  [
    'POST',
    `/accounting/fixed-assets/depreciations/${id}/post`,
    'accounting.fixedAssets.depreciationPost',
    erpFixedAssetSchema,
  ],
  [
    'POST',
    `/accounting/fixed-assets/${id}/dispose`,
    'accounting.fixedAssets.dispose',
    erpFixedAssetSchema,
  ],
  [
    'GET',
    '/accounting/references',
    'accounting.references',
    erpAccountingReferencesSchema,
  ],
  [
    'POST',
    '/accounting/references/accounts',
    'accounting.accounts.collection',
    erpAccountingAccountSchema,
  ],
  [
    'PATCH',
    `/accounting/references/accounts/${id}`,
    'accounting.accounts.detail',
    erpAccountingAccountSchema,
  ],
  [
    'POST',
    '/accounting/references/journals',
    'accounting.journals.collection',
    erpAccountingJournalSchema,
  ],
  [
    'PATCH',
    `/accounting/references/journals/${id}`,
    'accounting.journals.detail',
    erpAccountingJournalSchema,
  ],
  [
    'GET',
    '/accounting/grand-livre',
    'accounting.grand-livre',
    erpGrandLivreReportSchema,
  ],
  ['GET', '/accounting/balance', 'accounting.balance', erpBalanceReportSchema],
  ['GET', '/documents', 'documents.collection', erpDocumentListSchema],
  ['POST', '/documents', 'documents.collection', erpDocumentSchema],
  ['GET', `/documents/${id}`, 'documents.detail', erpDocumentSchema],
  [
    'GET',
    `/documents/${id}/content`,
    'documents.content',
    erpDocumentContentSchema,
  ],
  [
    'POST',
    `/documents/${id}/ocr/retry`,
    'documents.ocr.retry',
    erpDocumentSchema,
  ],
  [
    'POST',
    `/documents/${id}/ocr/validate`,
    'documents.ocr.validate',
    erpDocumentSchema,
  ],
  [
    'POST',
    `/documents/${id}/create-supplier-invoice`,
    'documents.create-supplier-invoice',
    erpSupplierInvoiceSchema,
  ],
  [
    'GET',
    '/operations/expense-notes',
    'operations.expense-notes',
    erpExpenseNoteListSchema,
  ],
  [
    'POST',
    '/operations/expense-notes',
    'operations.expense-notes',
    erpExpenseNoteSchema,
  ],
  [
    'POST',
    `/operations/expense-notes/${id}/submit`,
    'operations.expense-note.submit',
    erpExpenseNoteSchema,
  ],
  [
    'PATCH',
    `/operations/expense-notes/${id}/decision`,
    'operations.expense-note.decision',
    erpExpenseNoteSchema,
  ],
  [
    'POST',
    `/operations/expense-notes/${id}/pay`,
    'operations.expense-note.payment',
    erpExpenseNoteSchema,
  ],
  [
    'GET',
    '/operations/analytics',
    'operations.analytics',
    erpAnalyticAxisListSchema,
  ],
  [
    'POST',
    '/operations/analytics',
    'operations.analytics',
    erpAnalyticAxisSchema,
  ],
  [
    'POST',
    '/operations/analytics/allocations',
    'operations.analytics.allocations',
    erpAnalyticAllocationSchema,
  ],
  ['GET', '/operations/budgets', 'operations.budgets', erpBudgetListSchema],
  ['POST', '/operations/budgets', 'operations.budgets', erpBudgetSchema],
  [
    'POST',
    `/operations/budgets/${id}/approve`,
    'operations.budget.approve',
    erpBudgetSchema,
  ],
  [
    'GET',
    `/operations/budgets/${id}/variance`,
    'operations.budget.variance',
    erpBudgetVarianceSchema,
  ],
  [
    'GET',
    '/operations/recurring-invoices',
    'operations.recurring-invoices',
    erpRecurringInvoiceListSchema,
  ],
  [
    'POST',
    '/operations/recurring-invoices',
    'operations.recurring-invoices',
    erpRecurringInvoiceSchema,
  ],
  [
    'PATCH',
    `/operations/recurring-invoices/${id}/status`,
    'operations.recurring-invoice.status',
    erpRecurringInvoiceSchema,
  ],
  [
    'POST',
    '/operations/recurring-invoices/run',
    'operations.recurring-invoices.run',
    erpRecurringInvoiceRunSchema,
  ],
  [
    'GET',
    '/operations/exchange-rates',
    'operations.exchange-rates',
    erpExchangeRateListSchema,
  ],
  [
    'POST',
    '/operations/exchange-rates',
    'operations.exchange-rates',
    erpExchangeRateSchema,
  ],
  [
    'GET',
    '/operations/portal-access',
    'operations.portal-access',
    erpPortalAccessListSchema,
  ],
  [
    'POST',
    '/operations/portal-access',
    'operations.portal-access',
    erpPortalAccessGrantSchema,
  ],
  [
    'POST',
    `/operations/portal-access/${id}/revoke`,
    'operations.portal-access.revoke',
    erpPortalAccessSchema,
  ],
  [
    'POST',
    `/operations/portal-access/${id}/resend`,
    'operations.portal-access.resend',
    erpPortalInvitationSchema,
  ],
  [
    'POST',
    `/operations/portal-access/${id}/renew`,
    'operations.portal-access.renew',
    erpPortalAccessRenewSchema,
  ],
  [
    'GET',
    `/operations/portal-access/${id}/history`,
    'operations.portal-access.history',
    erpPortalAccessHistorySchema,
  ],
  [
    'GET',
    '/portal-admin/requests',
    'portal.admin.requests',
    clientPortalRequestListSchema,
  ],
  [
    'POST',
    `/portal-admin/requests/${id}/comments`,
    'portal.admin.comment',
    clientPortalCommentSchema,
  ],
  [
    'PATCH',
    `/portal-admin/requests/${id}`,
    'portal.admin.request.update',
    clientPortalRequestSchema,
  ],
  [
    'GET',
    '/fiscal/declarations',
    'fiscal.declarations',
    erpTaxDeclarationListSchema,
  ],
  [
    'POST',
    '/fiscal/tva/calculate',
    'fiscal.tva.calculate',
    erpTaxDeclarationSchema,
  ],
  [
    'GET',
    '/fiscal/tva/prorata',
    'fiscal.tva.prorata',
    erpTvaProrataPeriodListSchema,
  ],
  [
    'POST',
    '/fiscal/tva/prorata/calculate',
    'fiscal.tva.prorata.calculate',
    erpTvaProrataPeriodSchema,
  ],
  [
    'GET',
    '/fiscal/tva/prorata/annual',
    'fiscal.tva.prorata.annual',
    erpAnnualTvaProrataSchema,
  ],
  [
    'POST',
    '/fiscal/tva/prorata/annual/post',
    'fiscal.tva.prorata.annual.post',
    erpTvaProrataPostingSchema,
  ],
  [
    'POST',
    '/fiscal/is/calculate',
    'fiscal.is.calculate',
    erpTaxDeclarationSchema,
  ],
  [
    'PATCH',
    `/fiscal/declarations/${id}/status`,
    'fiscal.declaration.status',
    erpTaxDeclarationSchema,
  ],
  [
    'GET',
    `/fiscal/declarations/${id}/simpl`,
    'fiscal.declaration.simpl',
    erpFileExportSchema,
  ],
  [
    'GET',
    `/fiscal/declarations/${id}/adc080f`,
    'fiscal.declaration.adc080f',
    erpFileExportSchema,
  ],
  [
    'GET',
    `/fiscal/declarations/${id}/is-xml`,
    'fiscal.declaration.is-xml',
    erpFileExportSchema,
  ],
  [
    'GET',
    `/fiscal/declarations/${id}/payments`,
    'fiscal.declaration.payments',
    erpTaxPaymentListSchema,
  ],
  [
    'GET',
    `/fiscal/declarations/${id}/payment-candidates`,
    'fiscal.declaration.payment-candidates',
    erpTaxPaymentCandidateListSchema,
  ],
  [
    'POST',
    `/fiscal/declarations/${id}/payments`,
    'fiscal.declaration.payments',
    erpTaxPaymentSchema,
  ],
  ['GET', '/fiscal/deadlines', 'fiscal.deadlines', erpFiscalDeadlineListSchema],
  [
    'POST',
    '/fiscal/deadlines/seed',
    'fiscal.deadlines.seed',
    erpFiscalDeadlineListSchema,
  ],
  [
    'PATCH',
    `/fiscal/deadlines/${id}/complete`,
    'fiscal.deadline.complete',
    erpFiscalDeadlineSchema,
  ],
  [
    'GET',
    '/accounting/lettrage/suggestions',
    'accounting.lettrage.suggestions',
    erpLettrageSuggestionsSchema,
  ],
  [
    'POST',
    '/accounting/lettrage/match',
    'accounting.lettrage.match',
    erpLettrageMatchSchema,
  ],
  [
    'POST',
    '/accounting/lettrage/unmatch',
    'accounting.lettrage.unmatch',
    erpLettrageMatchSchema,
  ],
  [
    'GET',
    '/accounting-compliance/exercises',
    'compliance.exercises',
    erpExerciseListSchema,
  ],
  [
    'POST',
    '/accounting-compliance/exercises',
    'compliance.exercises',
    erpExerciseSchema,
  ],
  [
    'POST',
    `/accounting-compliance/exercises/${id}/review`,
    'compliance.exercise.review',
    erpAccountingReviewTaskListSchema,
  ],
  [
    'GET',
    `/accounting-compliance/exercises/${id}/review-dossier`,
    'compliance.exercise.review-dossier',
    erpAccountingReviewDossierSchema,
  ],
  [
    'POST',
    `/accounting-compliance/exercises/${id}/review-refresh`,
    'compliance.exercise.review-refresh',
    erpAccountingReviewDossierSchema,
  ],
  [
    'GET',
    `/accounting-compliance/exercises/${id}/review-export`,
    'compliance.exercise.review-export',
    erpAccountingReviewExportSchema,
  ],
  [
    'PATCH',
    `/accounting-compliance/review-tasks/${id}`,
    'compliance.review-task',
    erpAccountingReviewTaskSchema,
  ],
  [
    'POST',
    `/accounting-compliance/review-tasks/${id}/decision`,
    'compliance.review-task.decision',
    erpAccountingReviewTaskSchema,
  ],
  [
    'PATCH',
    `/accounting-compliance/review-accounts/${id}`,
    'compliance.review-account',
    erpAccountingReviewAccountSchema,
  ],
  [
    'POST',
    `/accounting-compliance/periods/${id}/close`,
    'compliance.period.close',
    erpAccountingPeriodSchema,
  ],
  [
    'POST',
    `/accounting-compliance/periods/${id}/reopen`,
    'compliance.period.reopen',
    erpAccountingPeriodSchema,
  ],
  [
    'POST',
    `/accounting-compliance/exercises/${id}/close`,
    'compliance.exercise.close',
    erpExerciseClosingResultSchema,
  ],
  [
    'GET',
    `/accounting-compliance/exercises/${id}/statements`,
    'compliance.exercise.statements',
    erpFinancialStatementsSchema,
  ],
  [
    'GET',
    `/accounting-compliance/exercises/${id}/fec`,
    'compliance.exercise.fec',
    erpFecExportSchema,
  ],
  [
    'POST',
    '/accounting-compliance/fec/import',
    'compliance.fec.import',
    erpFecImportResultSchema,
  ],
  [
    'GET',
    `/liasse/exercises/${id}/tables`,
    'liasse.tables',
    erpLiasseTableSummaryListSchema,
  ],
  [
    'GET',
    `/liasse/exercises/${id}/validation`,
    'liasse.validation',
    erpLiasseValidationSchema,
  ],
  [
    'GET',
    `/liasse/exercises/${id}/tables/T12`,
    'liasse.table',
    erpLiasseTableDetailSchema,
  ],
  [
    'PUT',
    `/liasse/exercises/${id}/tables/T12/rows/ASSOCIE_1`,
    'liasse.row',
    erpLiasseRowSchema,
  ],
  [
    'DELETE',
    `/liasse/exercises/${id}/tables/T12/rows/ASSOCIE_1`,
    'liasse.row',
    erpLiasseDeleteResultSchema,
  ],
  [
    'GET',
    `/liasse/exercises/${id}/export`,
    'liasse.export',
    erpLiasseExportSchema,
  ],
  [
    'GET',
    '/liasse/submissions',
    'regulatory.submissions',
    erpRegulatorySubmissionListSchema,
  ],
  [
    'PATCH',
    `/liasse/submissions/${id}/external-validation`,
    'regulatory.submission.validation',
    erpRegulatorySubmissionSchema,
  ],
  [
    'GET',
    '/ai-accounting/status',
    'ai-accounting.status',
    erpAiAccountingStatusSchema,
  ],
  [
    'GET',
    '/ai-accounting/suggestions',
    'ai-accounting.suggestions',
    erpAiAccountingSuggestionListSchema,
  ],
  [
    'GET',
    '/ai-accounting/rules',
    'ai-accounting.rules',
    erpAiCategorizationRuleListSchema,
  ],
  [
    'POST',
    '/ai-accounting/rules',
    'ai-accounting.rules',
    erpAiCategorizationRuleSchema,
  ],
  [
    'PATCH',
    `/ai-accounting/rules/${id}`,
    'ai-accounting.rule.update',
    erpAiCategorizationRuleSchema,
  ],
  [
    'POST',
    `/ai-accounting/rules/${id}/deactivate`,
    'ai-accounting.rule.deactivate',
    erpAiCategorizationRuleSchema,
  ],
  [
    'POST',
    '/ai-accounting/categorize',
    'ai-accounting.categorize',
    erpAiAccountingSuggestionBatchSchema,
  ],
  [
    'POST',
    '/ai-accounting/reconcile',
    'ai-accounting.reconcile',
    erpAiAccountingSuggestionBatchSchema,
  ],
  [
    'PATCH',
    `/ai-accounting/suggestions/${id}`,
    'ai-accounting.suggestion.review',
    erpAiAccountingSuggestionSchema,
  ],
  [
    'POST',
    '/ai-accounting/safe-query',
    'ai-accounting.safe-query',
    erpAiAccountingSafeQueryResultSchema,
  ],
  [
    'GET',
    '/ai-accounting/conversations',
    'ai-accounting.conversations',
    erpAiAccountingConversationListSchema,
  ],
  [
    'POST',
    '/ai-accounting/ask',
    'ai-accounting.ask',
    erpAiAccountingAnswerSchema,
  ],
  ['GET', '/marketing/overview', 'marketing.overview', marketingOverviewSchema],
  [
    'GET',
    '/marketing/contacts',
    'marketing.contacts.collection',
    marketingContactListSchema,
  ],
  [
    'POST',
    '/marketing/contacts/import-tiers',
    'marketing.contacts.importTiers',
    marketingTierImportResultSchema,
  ],
  [
    'POST',
    `/marketing/contacts/${id}/consent`,
    'marketing.contacts.consent',
    marketingContactSchema,
  ],
  [
    'GET',
    '/marketing/segments',
    'marketing.segments.collection',
    marketingSegmentListSchema,
  ],
  [
    'POST',
    '/marketing/segments',
    'marketing.segments.collection',
    marketingSegmentSchema,
  ],
  [
    'POST',
    `/marketing/segments/${id}/sync`,
    'marketing.segments.sync',
    marketingSegmentSyncResultSchema,
  ],
  [
    'GET',
    '/marketing/campaigns',
    'marketing.campaigns.collection',
    marketingCampaignListSchema,
  ],
  [
    'POST',
    '/marketing/campaigns',
    'marketing.campaigns.collection',
    marketingCampaignSchema,
  ],
  [
    'POST',
    `/marketing/campaigns/${id}/send`,
    'marketing.campaigns.send',
    marketingCampaignSchema,
  ],
  [
    'POST',
    `/marketing/campaigns/${id}/refresh`,
    'marketing.campaigns.refresh',
    marketingCampaignSchema,
  ],
  [
    'GET',
    '/marketing/automations',
    'marketing.automations.collection',
    marketingAutomationListSchema,
  ],
  [
    'POST',
    '/marketing/automations',
    'marketing.automations.collection',
    marketingAutomationSchema,
  ],
  [
    'POST',
    `/marketing/automations/${id}/activate`,
    'marketing.automations.activate',
    marketingAutomationSchema,
  ],
  [
    'POST',
    `/marketing/automations/${id}/pause`,
    'marketing.automations.pause',
    marketingAutomationSchema,
  ],
  [
    'GET',
    '/marketing/scoring-rules',
    'marketing.scoringRules.collection',
    marketingScoringRuleListSchema,
  ],
  [
    'POST',
    '/marketing/scoring-rules',
    'marketing.scoringRules.collection',
    marketingScoringRuleSchema,
  ],
  [
    'POST',
    `/marketing/scoring-rules/${id}/toggle`,
    'marketing.scoringRules.toggle',
    marketingScoringRuleSchema,
  ],
  [
    'GET',
    '/marketing/events',
    'marketing.events.collection',
    marketingEventListSchema,
  ],
  [
    'POST',
    '/marketing/events',
    'marketing.events.collection',
    marketingEventSchema,
  ],
  ['GET', '/payroll/employees', 'payroll.employees', erpEmployeeListSchema],
  ['GET', '/payroll/payslips', 'payroll.payslips', erpPayslipListSchema],
  [
    'POST',
    '/payroll/payslips/generate',
    'payroll.payslip.generate',
    erpPayslipSchema,
  ],
  [
    'POST',
    `/payroll/payslips/${id}/validate`,
    'payroll.payslip.validate',
    erpPayslipSchema,
  ],
  [
    'POST',
    `/payroll/payslips/${id}/pay`,
    'payroll.payslip.pay',
    erpPayslipSchema,
  ],
  ['GET', '/payroll/cnss/bds', 'payroll.cnss.bds', erpRegulatoryFileSchema],
  [
    'GET',
    '/attendance/policies',
    'attendance.policies',
    attendancePolicyListSchema,
  ],
  [
    'POST',
    '/attendance/policies',
    'attendance.policies',
    attendancePolicySchema,
  ],
  [
    'PATCH',
    `/attendance/policies/${id}`,
    'attendance.policy.detail',
    attendancePolicySchema,
  ],
  [
    'GET',
    '/attendance/assignments',
    'attendance.assignments',
    attendanceAssignmentListSchema,
  ],
  [
    'POST',
    '/attendance/assignments',
    'attendance.assignments',
    attendanceAssignmentSchema,
  ],
  [
    'GET',
    '/attendance/records',
    'attendance.records',
    attendanceRecordListSchema,
  ],
  ['POST', '/attendance/records', 'attendance.records', attendanceRecordSchema],
  [
    'POST',
    `/attendance/records/${id}/submit`,
    'attendance.record.submit',
    attendanceRecordSchema,
  ],
  [
    'POST',
    `/attendance/records/${id}/decision`,
    'attendance.record.decision',
    attendanceRecordSchema,
  ],
  [
    'GET',
    '/attendance/periods',
    'attendance.periods',
    attendancePeriodListSchema,
  ],
  [
    'POST',
    '/attendance/periods/recompute',
    'attendance.period.recompute',
    attendancePeriodSchema,
  ],
  [
    'POST',
    `/attendance/periods/${id}/approve`,
    'attendance.period.approve',
    attendancePeriodSchema,
  ],
  [
    'GET',
    '/talent/recruitment/jobs',
    'talent.recruitment.jobs',
    talentRecruitmentJobListSchema,
  ],
  [
    'POST',
    '/talent/recruitment/jobs',
    'talent.recruitment.jobs',
    talentRecruitmentJobSchema,
  ],
  [
    'PATCH',
    `/talent/recruitment/jobs/${id}/status`,
    'talent.recruitment.job.status',
    talentRecruitmentJobSchema,
  ],
  [
    'GET',
    '/talent/recruitment/applications',
    'talent.recruitment.applications',
    talentRecruitmentApplicationListSchema,
  ],
  [
    'POST',
    '/talent/recruitment/applications',
    'talent.recruitment.applications',
    talentRecruitmentApplicationSchema,
  ],
  [
    'PATCH',
    `/talent/recruitment/applications/${id}/status`,
    'talent.recruitment.application.status',
    talentRecruitmentApplicationSchema,
  ],
  [
    'POST',
    `/talent/recruitment/applications/${id}/interviews`,
    'talent.recruitment.interviews',
    talentRecruitmentInterviewSchema,
  ],
  [
    'PATCH',
    `/talent/recruitment/interviews/${id}`,
    'talent.recruitment.interview.detail',
    talentRecruitmentInterviewSchema,
  ],
  [
    'POST',
    `/talent/recruitment/applications/${id}/hire`,
    'talent.recruitment.hire',
    talentRecruitmentApplicationSchema,
  ],
  [
    'GET',
    '/talent/training/courses',
    'talent.training.courses',
    talentTrainingCourseListSchema,
  ],
  [
    'POST',
    '/talent/training/courses',
    'talent.training.courses',
    talentTrainingCourseSchema,
  ],
  [
    'GET',
    '/talent/training/sessions',
    'talent.training.sessions',
    talentTrainingSessionListSchema,
  ],
  [
    'POST',
    '/talent/training/sessions',
    'talent.training.sessions',
    talentTrainingSessionSchema,
  ],
  [
    'PATCH',
    `/talent/training/sessions/${id}/status`,
    'talent.training.session.status',
    talentTrainingSessionSchema,
  ],
  [
    'GET',
    '/talent/training/enrollments',
    'talent.training.enrollments',
    talentTrainingEnrollmentListSchema,
  ],
  [
    'POST',
    '/talent/training/enrollments',
    'talent.training.enrollments',
    talentTrainingEnrollmentSchema,
  ],
  [
    'PATCH',
    `/talent/training/enrollments/${id}`,
    'talent.training.enrollment.detail',
    talentTrainingEnrollmentSchema,
  ],
  ['GET', '/talent/skills', 'talent.skills', talentSkillListSchema],
  ['POST', '/talent/skills', 'talent.skills', talentSkillSchema],
  [
    'GET',
    '/talent/employee-skills',
    'talent.employee-skills',
    talentEmployeeSkillListSchema,
  ],
  [
    'POST',
    '/talent/employee-skills',
    'talent.employee-skills',
    talentEmployeeSkillSchema,
  ],
  [
    'GET',
    '/talent/performance/cycles',
    'talent.performance.cycles',
    talentPerformanceCycleListSchema,
  ],
  [
    'POST',
    '/talent/performance/cycles',
    'talent.performance.cycles',
    talentPerformanceCycleSchema,
  ],
  [
    'PATCH',
    `/talent/performance/cycles/${id}/status`,
    'talent.performance.cycle.status',
    talentPerformanceCycleSchema,
  ],
  [
    'GET',
    '/talent/performance/reviews',
    'talent.performance.reviews',
    talentPerformanceReviewListSchema,
  ],
  [
    'POST',
    '/talent/performance/reviews',
    'talent.performance.reviews',
    talentPerformanceReviewSchema,
  ],
  [
    'PATCH',
    `/talent/performance/reviews/${id}`,
    'talent.performance.review.detail',
    talentPerformanceReviewSchema,
  ],
  [
    'GET',
    '/employee-portal/employees',
    'employee-portal.employees',
    employeePortalEmployeeListSchema,
  ],
  [
    'GET',
    '/employee-portal/dashboard',
    'employee-portal.dashboard',
    employeePortalDashboardSchema,
  ],
  [
    'POST',
    '/employee-portal/leaves',
    'employee-portal.leaves',
    erpLeaveRequestSchema,
  ],
  [
    'POST',
    `/employee-portal/leaves/${id}/cancel`,
    'employee-portal.leave.cancel',
    erpLeaveRequestSchema,
  ],
  [
    'POST',
    '/employee-portal/requests',
    'employee-portal.requests',
    employeePortalRequestSchema,
  ],
  [
    'POST',
    `/employee-portal/requests/${id}/cancel`,
    'employee-portal.request.cancel',
    employeePortalRequestSchema,
  ],
  [
    'GET',
    `/employee-portal/payslips/${id}/pdf`,
    'employee-portal.payslip.pdf',
    employeePortalFileSchema,
  ],
  [
    'GET',
    '/employee-portal/attestation',
    'employee-portal.attestation',
    employeePortalFileSchema,
  ],
  [
    'GET',
    `/employee-portal/documents/${id}/content`,
    'employee-portal.document.content',
    employeePortalFileSchema,
  ],
  [
    'GET',
    '/employee-portal/admin/requests',
    'employee-portal.admin.requests',
    employeePortalRequestListSchema,
  ],
  [
    'PATCH',
    `/employee-portal/admin/requests/${id}`,
    'employee-portal.admin.request.review',
    employeePortalRequestSchema,
  ],
  [
    'GET',
    '/payroll/regulatory/summary',
    'payroll.regulatory.summary',
    payrollRegulatorySummarySchema,
  ],
  [
    'GET',
    '/payroll/regulatory/rules',
    'payroll.regulatory.rules',
    payrollRuleListSchema,
  ],
  [
    'GET',
    '/payroll/regulatory/components',
    'payroll.regulatory.components',
    payrollComponentListSchema,
  ],
  [
    'GET',
    '/payroll/regulatory/controls',
    'payroll.regulatory.controls',
    payrollControlDefinitionListSchema,
  ],
  [
    'GET',
    '/payroll/regulatory/sources',
    'payroll.regulatory.sources',
    payrollLegalSourceListSchema,
  ],
  [
    'POST',
    '/payroll/regulatory/seed/morocco-2026',
    'payroll.regulatory.seed',
    payrollRegulatorySeedResultSchema,
  ],
  ['GET', '/hr-core/summary', 'hr-core.summary', hrCoreSummarySchema],
  ['GET', '/hr-core/access/me', 'hr-core.access.me', hrAccessContextSchema],
  [
    'GET',
    '/hr-core/access/administration',
    'hr-core.access.administration',
    hrAccessAdministrationSchema,
  ],
  [
    'POST',
    '/hr-core/access/grants',
    'hr-core.access.grants',
    hrAccessGrantSchema,
  ],
  [
    'GET',
    '/hr-core/establishments',
    'hr-core.establishments',
    hrEstablishmentListSchema,
  ],
  [
    'POST',
    '/hr-core/establishments',
    'hr-core.establishments',
    hrEstablishmentSchema,
  ],
  [
    'PATCH',
    `/hr-core/establishments/${id}`,
    'hr-core.establishment.detail',
    hrEstablishmentSchema,
  ],
  ['GET', '/hr-core/grades', 'hr-core.grades', hrGradeListSchema],
  ['POST', '/hr-core/grades', 'hr-core.grades', hrGradeSchema],
  ['PATCH', `/hr-core/grades/${id}`, 'hr-core.grade.detail', hrGradeSchema],
  [
    'GET',
    '/hr-core/cost-centers',
    'hr-core.cost-centers',
    hrCostCenterListSchema,
  ],
  ['POST', '/hr-core/cost-centers', 'hr-core.cost-centers', hrCostCenterSchema],
  [
    'PATCH',
    `/hr-core/cost-centers/${id}`,
    'hr-core.cost-center.detail',
    hrCostCenterSchema,
  ],
  ['GET', '/hr-core/teams', 'hr-core.teams', hrTeamListSchema],
  ['POST', '/hr-core/teams', 'hr-core.teams', hrTeamSchema],
  ['PATCH', `/hr-core/teams/${id}`, 'hr-core.team.detail', hrTeamSchema],
  [
    'GET',
    '/hr-core/work-locations',
    'hr-core.work-locations',
    hrWorkLocationListSchema,
  ],
  [
    'POST',
    '/hr-core/work-locations',
    'hr-core.work-locations',
    hrWorkLocationSchema,
  ],
  [
    'PATCH',
    `/hr-core/work-locations/${id}`,
    'hr-core.work-location.detail',
    hrWorkLocationSchema,
  ],
  [
    'GET',
    '/hr-core/departments',
    'hr-core.departments',
    hrDepartmentListSchema,
  ],
  ['POST', '/hr-core/departments', 'hr-core.departments', hrDepartmentSchema],
  [
    'PATCH',
    `/hr-core/departments/${id}`,
    'hr-core.department.detail',
    hrDepartmentSchema,
  ],
  [
    'GET',
    '/hr-core/job-positions',
    'hr-core.job-positions',
    hrJobPositionListSchema,
  ],
  [
    'POST',
    '/hr-core/job-positions',
    'hr-core.job-positions',
    hrJobPositionSchema,
  ],
  [
    'PATCH',
    `/hr-core/job-positions/${id}`,
    'hr-core.job-position.detail',
    hrJobPositionSchema,
  ],
  [
    'GET',
    '/hr-core/employee-import/template',
    'hr-core.employee-import.template',
    hrEmployeeImportTemplateSchema,
  ],
  [
    'POST',
    '/hr-core/employee-import/preview',
    'hr-core.employee-import.preview',
    hrEmployeeImportPreviewSchema,
  ],
  [
    'POST',
    '/hr-core/employee-import/commit',
    'hr-core.employee-import.commit',
    hrEmployeeImportCommitResultSchema,
  ],
  ['GET', '/hr-core/employees', 'hr-core.employees', hrEmployeeListSchema],
  [
    'GET',
    `/hr-core/employees/${id}`,
    'hr-core.employee.detail',
    hrEmployeeDetailSchema,
  ],
  [
    'PATCH',
    `/hr-core/employees/${id}/personal-details`,
    'hr-core.employee.personal-details',
    hrEmployeePrivateProfileSchema,
  ],
  [
    'POST',
    `/hr-core/employees/${id}/dependants`,
    'hr-core.employee.dependants',
    hrEmployeeDependantSchema,
  ],
  [
    'PATCH',
    `/hr-core/dependants/${id}`,
    'hr-core.dependant.detail',
    hrEmployeeDependantSchema,
  ],
  [
    'POST',
    `/hr-core/employees/${id}/emergency-contacts`,
    'hr-core.employee.emergency-contacts',
    hrEmployeeEmergencyContactSchema,
  ],
  [
    'PATCH',
    `/hr-core/emergency-contacts/${id}`,
    'hr-core.emergency-contact.detail',
    hrEmployeeEmergencyContactSchema,
  ],
  [
    'PATCH',
    `/hr-core/employees/${id}/bank-account`,
    'hr-core.employee.bank-account',
    hrEmployeeBankAccountSchema,
  ],
  [
    'POST',
    `/hr-core/employees/${id}/assignments`,
    'hr-core.employee.assignments',
    hrEmployeeAssignmentSchema,
  ],
  [
    'PATCH',
    `/hr-core/assignments/${id}/end`,
    'hr-core.assignment.end',
    hrEmployeeAssignmentSchema,
  ],
  ['GET', '/hr-core/deadlines', 'hr-core.deadlines', hrDeadlineCenterSchema],
  [
    'POST',
    `/hr-core/employees/${id}/documents`,
    'hr-core.employee.documents',
    hrEmployeeDocumentSchema,
  ],
  [
    'PATCH',
    `/hr-core/hr-documents/${id}`,
    'hr-core.document.detail',
    hrEmployeeDocumentSchema,
  ],
  [
    'POST',
    `/hr-core/hr-documents/${id}/versions`,
    'hr-core.document.versions',
    hrEmployeeDocumentSchema,
  ],
  [
    'GET',
    `/hr-core/hr-document-versions/${id}/content`,
    'hr-core.document-version.content',
    hrDocumentContentSchema,
  ],
  [
    'GET',
    '/hr-core/lifecycle-journeys',
    'hr-core.lifecycle-journeys',
    hrLifecycleJourneyListSchema,
  ],
  [
    'POST',
    '/hr-core/lifecycle-journeys',
    'hr-core.lifecycle-journeys',
    hrLifecycleJourneySchema,
  ],
  ['POST', '/hr-core/hiring', 'hr-core.hiring', hrLifecycleJourneySchema],
  [
    'PATCH',
    `/hr-core/lifecycle-tasks/${id}`,
    'hr-core.lifecycle-task.detail',
    hrLifecycleTaskSchema,
  ],
  [
    'PATCH',
    `/hr-core/lifecycle-journeys/${id}/status`,
    'hr-core.lifecycle-journey.status',
    hrLifecycleJourneySchema,
  ],
  [
    'POST',
    `/hr-core/employees/${id}/contracts`,
    'hr-core.employee.contracts',
    hrEmploymentContractSchema,
  ],
  [
    'PATCH',
    `/hr-core/contracts/${id}/status`,
    'hr-core.contract.status',
    hrEmploymentContractSchema,
  ],
  [
    'POST',
    `/hr-core/contracts/${id}/amendments`,
    'hr-core.contract.amendments',
    hrContractAmendmentSchema,
  ],
  [
    'PATCH',
    `/hr-core/amendments/${id}/status`,
    'hr-core.amendment.status',
    hrContractAmendmentSchema,
  ],
] as const;

describe('ERP Maroc route policy', () => {
  it.each(approvedRoutes)(
    'allows %s %s through the declared route %s',
    (method, path, routeId, responseSchema) => {
      const requiresAccountCode =
        routeId === 'accounting.grand-livre' ||
        routeId === 'accounting.lettrage.suggestions';
      const requiresExercise =
        routeId === 'fiscal.tva.prorata' ||
        routeId === 'fiscal.tva.prorata.annual';
      const requiresYear = routeId === 'fiscal.deadlines.seed';
      const query = requiresAccountCode
        ? { accountCode: '3421' }
        : requiresExercise
          ? { exerciceId: id }
          : requiresYear
            ? { year: '2026' }
            : {};
      const resolved = resolveErpRoute(method, path, query);

      expect(resolved.routeId).toBe(routeId);
      expect(resolved.upstreamPath).toBe(
        requiresAccountCode
          ? `${path}?accountCode=3421`
          : requiresExercise
            ? `${path}?exerciceId=${id}`
            : requiresYear
              ? `${path}?year=2026`
              : path,
      );
      const expectsPdf =
        routeId === 'invoices.pdf' || routeId === 'cheques.depositSlips.pdf';
      expect(resolved.kind).toBe(expectsPdf ? 'pdf' : 'json');
      expect(resolved.idempotency).toBe(
        requiredIdempotencyRoutes.has(`${method} ${path}`)
          ? 'required'
          : 'forbidden',
      );
      if (responseSchema !== undefined) {
        expect(resolved.responseSchema).toBe(responseSchema);
      }
    },
  );

  it('exports a deeply immutable policy with one entry per approved method/path', () => {
    expect(ERP_MAROC_ROUTE_POLICY).toHaveLength(approvedRoutes.length);
    expect(Object.isFrozen(ERP_MAROC_ROUTE_POLICY)).toBe(true);
    for (const route of ERP_MAROC_ROUTE_POLICY) {
      expect(Object.isFrozen(route)).toBe(true);
      expect(Object.isFrozen(route.queryKeys)).toBe(true);
    }
  });

  it('accepts UUID v7 exactly as the shared uuidSchema does', () => {
    expect(resolveErpRoute('GET', `/products/${uuidV7}`, {})).toMatchObject({
      routeId: 'products.detail',
      upstreamPath: `/products/${uuidV7}`,
    });
  });

  it('forwards a DAMANCOM BDS export with its period and format', () => {
    expect(
      resolveErpRoute('GET', '/payroll/cnss/bds', {
        periodKey: '2026-08',
        format: 'xml',
      }),
    ).toMatchObject({
      routeId: 'payroll.cnss.bds',
      upstreamPath: '/payroll/cnss/bds?periodKey=2026-08&format=xml',
      kind: 'json',
      idempotency: 'forbidden',
    });
  });

  it.each([
    ['GET', '/organisations'],
    ['POST', '/organisations'],
    ['DELETE', `/payments/${id}`],
    ['PUT', '/products'],
    ['TRACE', '/context'],
    ['GET', '/products/'],
    ['GET', '/products//'],
    ['GET', `/products/${id}/${id}`],
    ['GET', `/products/${id}/${otherId}`],
    ['GET', '/products/not-a-uuid'],
    ['GET', '/products/11111111-1111-1111-1111-111111111111'],
    ['GET', '/credit-notes/not-a-uuid'],
    ['GET', '/cheques/not-a-uuid'],
    ['GET', '/cheques/deposit-slips/not-a-uuid'],
    ['GET', '/credit-notes/%2e%2e'],
    ['GET', `/credit-notes/${id}/%2feligible-invoices`],
    ['GET', '/products/%2e%2e'],
    ['GET', '/products/%252e%252e'],
    ['GET', '/products/%2fcontext'],
    ['GET', '/products/%5ccontext'],
    ['GET', '/products\\context'],
    ['GET', 'https://attacker.test/products'],
    ['GET', '//attacker.test/products'],
    ['GET', 'http:/attacker.test/products'],
    ['GET', '/products#fragment'],
    ['GET', '/products?limit=1'],
    ['GET', '/products/%'],
    ['GET', '/products/%GG'],
  ])('rejects %s %s', (method, path) => {
    expect(() => resolveErpRoute(method, path, {})).toThrow(
      'ERP route is not allowed',
    );
  });

  it('builds query strings only from normalized allowlisted values', () => {
    expect(
      resolveErpRoute('GET', '/payments', {
        status: 'POSTED',
        kind: 'RECEIPT',
        method: 'BANK_TRANSFER',
        tierId: id,
        invoiceId: otherId,
        from: '2026-07-01',
        to: '2026-07-31',
        cursor: id,
        limit: '100',
      }).upstreamPath,
    ).toBe(
      `/payments?status=POSTED&kind=RECEIPT&method=BANK_TRANSFER&tierId=${id}&invoiceId=${otherId}&from=2026-07-01&to=2026-07-31&cursor=${id}&limit=100`,
    );
    expect(
      resolveErpRoute('GET', '/cheques', {
        direction: 'RECEIVED',
        instrumentType: 'CHEQUE',
        status: 'IN_PORTFOLIO',
        bankAccountId: id,
        dueBefore: '2026-08-31',
        search: 'Atlas 001',
        limit: '50',
      }).upstreamPath,
    ).toBe(
      `/cheques?direction=RECEIVED&instrumentType=CHEQUE&status=IN_PORTFOLIO&bankAccountId=${id}&dueBefore=2026-08-31&search=Atlas+001&limit=50`,
    );
    expect(
      resolveErpRoute('GET', '/cheques/alerts', {
        horizonDays: '15',
        staleDepositDays: '5',
        lowBookThreshold: '10',
      }).upstreamPath,
    ).toBe(
      '/cheques/alerts?horizonDays=15&staleDepositDays=5&lowBookThreshold=10',
    );
    expect(
      resolveErpRoute('GET', '/invoices', { cursor: id, limit: '50' })
        .upstreamPath,
    ).toBe(`/invoices?cursor=${id}&limit=50`);
    expect(
      resolveErpRoute('GET', `/payments/${id}/eligible-invoices`, {
        cursor: otherId,
        limit: '25',
      }).upstreamPath,
    ).toBe(`/payments/${id}/eligible-invoices?cursor=${otherId}&limit=25`);
    expect(
      resolveErpRoute('GET', '/credit-notes', {
        status: 'VALIDATED',
        tierId: id,
        invoiceId: otherId,
        from: '2026-07-01',
        to: '2026-07-31',
        cursor: id,
        limit: '100',
      }).upstreamPath,
    ).toBe(
      `/credit-notes?status=VALIDATED&tierId=${id}&invoiceId=${otherId}&from=2026-07-01&to=2026-07-31&cursor=${id}&limit=100`,
    );
    expect(
      resolveErpRoute('GET', `/credit-notes/${id}/eligible-invoices`, {
        cursor: otherId,
        limit: '25',
      }).upstreamPath,
    ).toBe(`/credit-notes/${id}/eligible-invoices?cursor=${otherId}&limit=25`);
    expect(
      resolveErpRoute('GET', '/reminders', {
        status: 'PROPOSED',
        level: 'LEVEL_1',
        cursor: id,
        limit: '10',
      }).upstreamPath,
    ).toBe(`/reminders?status=PROPOSED&level=LEVEL_1&cursor=${id}&limit=10`);
    expect(
      resolveErpRoute('GET', '/accounting/entries', {
        status: 'LOCKED',
        sourceType: 'REVERSAL',
        from: '2026-07-01',
        to: '2026-07-31',
        cursor: id,
        limit: '25',
      }).upstreamPath,
    ).toBe(
      `/accounting/entries?status=LOCKED&sourceType=REVERSAL&from=2026-07-01&to=2026-07-31&cursor=${id}&limit=25`,
    );
    expect(
      resolveErpRoute('GET', '/accounting/grand-livre', {
        accountCode: '3421',
        from: '2026-07-01',
        to: '2026-07-31',
        includeDraft: 'true',
      }).upstreamPath,
    ).toBe(
      '/accounting/grand-livre?accountCode=3421&from=2026-07-01&to=2026-07-31&includeDraft=true',
    );
    expect(
      resolveErpRoute('GET', '/accounting/balance', {
        from: '2026-07-01',
        to: '2026-07-31',
      }).upstreamPath,
    ).toBe('/accounting/balance?from=2026-07-01&to=2026-07-31');
    expect(
      resolveErpRoute('GET', '/accounting/lettrage/suggestions', {
        accountCode: '3421',
      }).upstreamPath,
    ).toBe('/accounting/lettrage/suggestions?accountCode=3421');
    expect(
      resolveErpRoute('GET', `/liasse/exercises/${id}/export`, {
        format: 'xlsx',
      }).upstreamPath,
    ).toBe(`/liasse/exercises/${id}/export?format=xlsx`);
    expect(
      resolveErpRoute('GET', '/fiscal/tva/prorata', {
        exerciceId: id,
      }).upstreamPath,
    ).toBe(`/fiscal/tva/prorata?exerciceId=${id}`);
    expect(
      resolveErpRoute('GET', `/fiscal/declarations/${id}/adc080f`, {
        regime: 'ENCAISSEMENT',
      }).upstreamPath,
    ).toBe(`/fiscal/declarations/${id}/adc080f?regime=ENCAISSEMENT`);
    expect(
      resolveErpRoute('POST', '/fiscal/deadlines/seed', {
        year: '2026',
      }).upstreamPath,
    ).toBe('/fiscal/deadlines/seed?year=2026');
    expect(
      resolveErpRoute('GET', '/documents', {
        search: 'facture atlas',
        type: 'SUPPLIER_INVOICE',
        tag: 'juillet',
      }).upstreamPath,
    ).toBe('/documents?search=facture+atlas&type=SUPPLIER_INVOICE&tag=juillet');
  });

  it.each([
    ['/products', { limit: '10' }],
    ['/invoices', { surprise: '1' }],
    ['/invoices', { limit: '01' }],
    ['/invoices', { limit: ' 1' }],
    ['/invoices', { limit: '101' }],
    ['/invoices', { cursor: 'not-a-uuid' }],
    ['/payments', { status: 'posted' }],
    ['/cheques', { direction: 'INBOUND' }],
    ['/cheques', { status: 'PAID' }],
    ['/cheques', { dueBefore: '2026-02-30' }],
    ['/cheques', { search: 'Atlas\nAdmin' }],
    ['/cheques/alerts', { horizonDays: '0' }],
    ['/cheques/alerts', { staleDepositDays: '31' }],
    ['/cheques/alerts', { lowBookThreshold: '101' }],
    ['/cheques/deposit-slips/eligible', { bankAccountId: 'not-a-uuid' }],
    ['/credit-notes', { status: 'POSTED' }],
    ['/credit-notes', { surprise: '1' }],
    [`/credit-notes/${id}/eligible-invoices`, { status: 'VALIDATED' }],
    ['/payments', { method: 'WIRE' }],
    ['/payments', { from: '2026-07-31', to: '2026-07-01' }],
    ['/reminders', { level: 'LEVEL_4' }],
    ['/reminders', { status: ['PROPOSED', 'SENT'] }],
    ['/reminders', { limit: 10 }],
    ['/accounting/entries', { status: 'POSTED' }],
    ['/accounting/entries', { sourceType: 'QUOTE' }],
    ['/accounting/grand-livre', {}],
    ['/accounting/grand-livre', { accountCode: '3421/../admin' }],
    ['/accounting/grand-livre', { accountCode: '3421', includeDraft: 'false' }],
    ['/accounting/balance', { includeDraft: 'yes' }],
    ['/accounting/balance', { from: '2026-07-31', to: '2026-07-01' }],
    ['/accounting/lettrage/suggestions', {}],
    ['/accounting/lettrage/suggestions', { accountCode: '3421/../admin' }],
    ['/fiscal/tva/prorata', {}],
    ['/fiscal/tva/prorata', { exerciceId: 'not-a-uuid' }],
    [`/fiscal/declarations/${id}/adc080f`, { regime: 'CASH' }],
    ['/fiscal/deadlines/seed', { year: '026' }],
    ['/fiscal/deadlines/seed', { year: '1999' }],
    ['/documents', { type: 'INVOICE' }],
    ['/documents', { search: 'facture\nadmin' }],
    ['/documents', { tag: 'x'.repeat(121) }],
  ])('rejects non-normalized or unauthorized query for %s', (path, query) => {
    expect(() => resolveErpRoute('GET', path, query)).toThrow(
      'ERP route is not allowed',
    );
  });

  it('rejects duplicate URLSearchParams keys', () => {
    const query = new URLSearchParams();
    query.append('limit', '10');
    query.append('limit', '20');

    expect(() => resolveErpRoute('GET', '/invoices', query)).toThrow(
      'ERP route is not allowed',
    );
  });
});
