export const erpMarocPortalPage = `<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Portail Zowka</title>
  <style>
    :root{color-scheme:light;--ink:#172126;--muted:#66747a;--line:#d9e0e2;--paper:#fff;--soft:#f4f7f7;--brand:#087f5b;--brand2:#173b45;--danger:#c92a2a}
    *{box-sizing:border-box}body{margin:0;background:var(--soft);color:var(--ink);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    header{height:64px;background:var(--brand2);color:white;display:flex;align-items:center;justify-content:space-between;padding:0 28px}header strong{font-size:20px}header span{color:#d6e7e4}
    nav{display:flex;gap:4px;padding:14px 24px 0;background:var(--paper);border-bottom:1px solid var(--line)}nav button{border:0;background:transparent;padding:11px 14px;color:var(--muted);font-weight:600;cursor:pointer;border-bottom:2px solid transparent}nav button.active{color:var(--brand);border-color:var(--brand)}
    main{max-width:1180px;margin:22px auto;padding:0 22px 40px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}h1{font-size:22px;margin:0}h2{font-size:16px;margin:0 0 12px}
    button,.button{border:1px solid var(--line);background:white;color:var(--ink);height:36px;padding:0 13px;font-weight:600;cursor:pointer;border-radius:6px}.primary{background:var(--brand);color:white;border-color:var(--brand)}button:disabled{opacity:.5;cursor:not-allowed}
    .panel{background:var(--paper);border:1px solid var(--line);border-radius:6px;padding:18px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.metric{padding:14px;background:var(--soft);border-left:3px solid var(--brand)}.metric b{display:block;font-size:18px}.muted{color:var(--muted)}
    table{width:100%;border-collapse:collapse;background:white}th,td{text-align:left;padding:11px 10px;border-bottom:1px solid var(--line)}th{font-size:12px;text-transform:uppercase;color:var(--muted)}td.amount{text-align:right;font-variant-numeric:tabular-nums}.status{font-size:12px;font-weight:700;color:var(--brand)}
    form{display:grid;gap:12px}label{display:grid;gap:5px;font-weight:600}input,select,textarea{width:100%;border:1px solid #b8c3c7;border-radius:5px;padding:9px 10px;font:inherit;background:white}textarea{min-height:100px;resize:vertical}.row{display:flex;gap:10px;align-items:center}.row>*{flex:1}.request{border-top:1px solid var(--line);padding:14px 0}.request:first-child{border-top:0}.comment{margin:8px 0;padding:9px 11px;background:var(--soft);border-left:3px solid #9eacad}.hidden{display:none!important}.error{color:var(--danger);font-weight:600;padding:12px;background:#fff5f5;border:1px solid #ffc9c9;border-radius:5px}.empty{padding:30px;text-align:center;color:var(--muted)}
    @media(max-width:720px){header{padding:0 16px}.grid{grid-template-columns:1fr}nav{overflow:auto;padding-left:10px}main{padding:0 12px}.row{display:grid}.table-wrap{overflow:auto}}
  </style>
</head>
<body>
  <header><strong>Zowka</strong><span id="identity">Portail client</span></header>
  <nav id="nav" class="hidden"><button data-view="dashboard" class="active">Synthese</button><button data-view="invoices">Factures</button><button data-view="requests">Demandes</button><button data-view="notifications">Notifications</button></nav>
  <main><div id="login" class="panel"><h1>Acces au portail</h1><p class="muted">Ouvrez le lien securise transmis par votre entreprise.</p><div id="login-error" class="error hidden">Ce lien est invalide ou a expire.</div></div><div id="app" class="hidden"></div></main>
  <script nonce="zowka-portal">
    const state={token:'',session:null,invoices:[],requests:[],notifications:[],view:'dashboard'};
    const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const money=c=>new Intl.NumberFormat('fr-MA',{style:'currency',currency:'MAD'}).format((c||0)/100);
    const date=v=>v?new Intl.DateTimeFormat('fr-MA').format(new Date(v)):'-';
    const downloadFile=file=>{const bytes=Uint8Array.from(atob(file.contentBase64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:file.mimeType}));const link=document.createElement('a');link.href=url;link.download=file.filename;link.click();URL.revokeObjectURL(url)};
    async function api(path,options={}){const response=await fetch('/portal-api'+path,{...options,headers:{'Authorization':'Bearer '+state.token,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw new Error('HTTP '+response.status);return response.json()}
    async function boot(){const hash=new URLSearchParams(location.hash.slice(1));state.token=hash.get('token')||localStorage.getItem('zowkaPortalToken')||'';history.replaceState(null,'',location.pathname);if(!state.token)return;try{state.session=await api('/session');localStorage.setItem('zowkaPortalToken',state.token);document.getElementById('login').classList.add('hidden');document.getElementById('nav').classList.remove('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('identity').textContent=state.session.customer.name;await refresh();}catch{localStorage.removeItem('zowkaPortalToken');document.getElementById('login-error').classList.remove('hidden')}}
    async function refresh(){const jobs=[api('/requests'),api('/notifications')];if(state.session.permissions.canViewInvoices)jobs.push(api('/invoices'));const result=await Promise.all(jobs);state.requests=result[0];state.notifications=result[1];state.invoices=result[2]||[];render()}
    function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const app=document.getElementById('app');if(state.view==='dashboard')app.innerHTML=dashboard();if(state.view==='invoices')app.innerHTML=invoices();if(state.view==='requests')app.innerHTML=requests();if(state.view==='notifications')app.innerHTML=notifications();bind()}
    function dashboard(){const open=state.requests.filter(r=>!['RESOLVED','CLOSED'].includes(r.status)).length;const unpaid=state.invoices.filter(i=>!['PAID','CANCELLED'].includes(i.status)).reduce((s,i)=>s+i.totalTtcCents,0);const unread=state.notifications.filter(n=>n.status==='UNREAD').length;return '<div class="toolbar"><h1>Synthese</h1></div><div class="grid"><div class="metric"><span class="muted">Factures a suivre</span><b>'+money(unpaid)+'</b></div><div class="metric"><span class="muted">Demandes ouvertes</span><b>'+open+'</b></div><div class="metric"><span class="muted">Notifications</span><b>'+unread+'</b></div></div>'}
    function invoices(){if(!state.session.permissions.canViewInvoices)return '<div class="error">Acces aux factures desactive.</div>';const rows=state.invoices.map(i=>'<tr><td>'+esc(i.number||'-')+'</td><td>'+esc(i.title)+'</td><td>'+date(i.issueDate)+'</td><td>'+date(i.dueDate)+'</td><td class="status">'+esc(i.status)+'</td><td class="amount">'+money(i.totalTtcCents)+'</td></tr>').join('');return '<div class="toolbar"><h1>Factures</h1></div><div class="panel table-wrap"><table><thead><tr><th>Numero</th><th>Objet</th><th>Emission</th><th>Echeance</th><th>Statut</th><th style="text-align:right">TTC</th></tr></thead><tbody>'+rows+'</tbody></table>'+(rows?'':'<div class="empty">Aucune facture disponible</div>')+'</div>'}
    function requests(){const items=state.requests.map(r=>'<article class="request"><div class="toolbar"><div><b>'+esc(r.subject)+'</b><div class="muted">'+esc(r.type)+' · '+date(r.createdAt)+'</div></div><span class="status">'+esc(r.status)+'</span></div><p>'+esc(r.description)+'</p>'+(r.comments||[]).map(c=>'<div class="comment">'+esc(c.body)+'</div>').join('')+'<div class="row">'+(r.documents||[]).map(d=>'<button type="button" data-document="'+d.document.id+'">'+esc(d.document.filename)+'</button>').join('')+'</div><form data-comment="'+r.id+'"><div class="row"><input name="body" placeholder="Ajouter un commentaire" required><button>Envoyer</button></div></form>'+(state.session.permissions.canSubmitDocuments?'<form data-upload="'+r.id+'"><div class="row"><input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required><button>Deposer</button></div></form>':'')+'</article>').join('');return '<div class="toolbar"><h1>Demandes</h1><button class="primary" id="new-request">Nouvelle demande</button></div><div id="request-form" class="panel hidden"><form id="create-request"><label>Type<select name="type"><option value="DOCUMENT">Document</option><option value="SUPPORT">Question</option><option value="INVOICE">Facture</option><option value="ACCOUNTING">Comptabilite</option><option value="OTHER">Autre</option></select></label><label>Objet<input name="subject" maxlength="180" required></label><label>Description<textarea name="description" maxlength="4000" required></textarea></label><button class="primary">Envoyer</button></form></div><div class="panel">'+(items||'<div class="empty">Aucune demande</div>')+'</div>'}
    function notifications(){const items=state.notifications.map(n=>'<article class="request"><div class="toolbar"><div><b>'+esc(n.title)+'</b><div class="muted">'+date(n.createdAt)+'</div></div>'+(n.status==='UNREAD'?'<button data-read="'+n.id+'">Marquer comme lue</button>':'<span class="status">Lue</span>')+'</div><p>'+esc(n.body)+'</p></article>').join('');return '<div class="toolbar"><h1>Notifications</h1></div><div class="panel">'+(items||'<div class="empty">Aucune notification</div>')+'</div>'}
    function bind(){document.getElementById('new-request')?.addEventListener('click',()=>document.getElementById('request-form').classList.toggle('hidden'));document.getElementById('create-request')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);await api('/requests',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await refresh()});document.querySelectorAll('[data-comment]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const body=new FormData(form).get('body');await api('/requests/'+form.dataset.comment+'/comments',{method:'POST',body:JSON.stringify({body})});await refresh()}));document.querySelectorAll('[data-upload]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const file=new FormData(form).get('file');if(!file||file.size>14*1024*1024)return alert('Fichier limite a 14 Mo');const contentBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});await api('/requests/'+form.dataset.upload+'/documents',{method:'POST',body:JSON.stringify({filename:file.name,contentBase64})});await refresh()}));document.querySelectorAll('[data-document]').forEach(button=>button.addEventListener('click',async()=>downloadFile(await api('/documents/'+button.dataset.document+'/content'))));document.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',async()=>{await api('/notifications/'+b.dataset.read+'/read',{method:'POST',body:'{}'});await refresh()}))}
    document.getElementById('nav').addEventListener('click',e=>{const button=e.target.closest('button[data-view]');if(button){state.view=button.dataset.view;render()}});boot();
  </script>
</body></html>`;
